/* Local TTS audio resolver — maps (text, lang) → file path under assets/audio/.
   Files are pre-generated by tools/generate-audio.py (run once after database updates).
   If a file doesn't exist, the <audio> element will 404 and speakText falls back to
   speechSynthesis (defined in flashcard_kosakata_bab1_10.js). */
(function () {
  async function hashText(text, lang) {
    const data = new TextEncoder().encode(`${lang}::${text}`);
    const buf = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(buf))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
      .slice(0, 16);
  }

  async function getAudioURL(text, lang) {
    if (!text) return null;
    const h = await hashText(text, lang);
    return { url: `assets/audio/${lang}/${h}.mp3`, cached: true };
  }

  // Backward-compat no-ops (kept so existing UI code doesn't break)
  async function getCacheCount() { return 0; }
  async function clearCache() { return true; }
  function precache() { return Promise.resolve(); }

  window.TTSCache = { getAudioURL, getCacheCount, clearCache, precache };
})();
