const BUNPO_QUIZ_QUESTIONS = [

  // ===== POLA 1: KB1はKB2です =====
  { cat:"copula", pola:"Pola 1: ～はです", topic:"Kalimat Dasar",
    solo:"ミラーさん（___）かいしゃいんです。",
    ch:["が","の","は","を"], ans:2,
    ex:"「は」adalah partikel topik. 「ミラーさんは」= 'Berbicara tentang Miller...'" },
  { cat:"copula", pola:"Pola 1: ～はです", topic:"Kalimat Dasar",
    dlg:[{s:"A",t:"たなかさん（___）せんせいですか。"},{s:"B",t:"はい、そうです。"}],
    ch:["を","は","が","に"], ans:1,
    ex:"「は」menandai topik kalimat. Tanaka sebagai topik diikuti「は」." },
  { cat:"copula", pola:"Pola 1: ～はです", topic:"Kalimat Dasar",
    solo:"これ（___）わたしの　ほんです。",
    ch:["は","が","を","で"], ans:0,
    ex:"「これは」= 'Ini adalah...'. 「は」menandai topik." },

  // ===== POLA 2: ではありません =====
  { cat:"copula", pola:"Pola 2: ～ではありません", topic:"Kalimat Negatif",
    dlg:[{s:"A",t:"やまださんは　がくせいですか。"},{s:"B",t:"いいえ、がくせい（___）。"}],
    ch:["ではありません","じゃないです","ではないです","すべて正しい"], ans:3,
    ex:"「ではありません」「じゃありません」「じゃないです」semuanya benar dan sama artinya — 'bukan'." },
  { cat:"copula", pola:"Pola 2: ～ではありません", topic:"Kalimat Negatif",
    solo:"これは　コーヒー（___）。にほんちゃです。",
    ch:["ではありません","ではあります","じゃあります","はありません"], ans:0,
    ex:"「ではありません」= bentuk negatif sopan dari です. 'Ini bukan kopi, ini teh Jepang'." },
  { cat:"copula", pola:"Pola 2: ～ではありません", topic:"Kalimat Negatif",
    dlg:[{s:"A",t:"あの　かたは　かちょうさんですか。"},{s:"B",t:"いいえ、かちょう（___）。ぶちょうです。"}],
    ch:["ではありません","ではいます","があります","をします"], ans:0,
    ex:"「ではありません」= 'bukan'. 'Bukan kepala seksi, beliau direktur'." },

  // ===== POLA 3: ～ですか =====
  { cat:"copula", pola:"Pola 3: ～ですか", topic:"Kalimat Tanya",
    dlg:[{s:"A",t:"おなまえは　なんですか。"},{s:"B",t:"（___）キムです。"}],
    ch:["わたしは","わたしが","わたしを","わたしで"], ans:0,
    ex:"Memperkenalkan diri → 「わたしは　〜です」. Topik diri sendiri pakai「は」." },
  { cat:"copula", pola:"Pola 3: ～ですか", topic:"Kalimat Tanya",
    solo:"A：おしごとは　なん（___）か。\nB：エンジニアです。",
    ch:["で","です","に","は"], ans:1,
    ex:"「なんですか」= 'Apa?' Partikel「か」di akhir membuat kalimat menjadi pertanyaan." },
  { cat:"copula", pola:"Pola 3: ～ですか", topic:"Kalimat Tanya",
    dlg:[{s:"A",t:"いまは　なんじ（___）。"},{s:"B",t:"ごじです。"}],
    ch:["ですか","ですね","ですよ","でしょう"], ans:0,
    ex:"「ですか」di akhir kalimat = bertanya. 「なんじですか」= 'Jam berapa?'" },

  // ===== POLA 4: KBのKBです =====
  { cat:"no", pola:"Pola 4: ～の～", topic:"Partikel の",
    solo:"これは　わたし（___）ほんです。",
    ch:["が","の","に","と"], ans:1,
    ex:"「の」menunjukkan kepemilikan. 「わたしのほん」= 'buku milik saya'." },
  { cat:"no", pola:"Pola 4: ～の～", topic:"Partikel の",
    solo:"たなかさんは　にほん（___）かいしゃいんです。",
    ch:["で","の","に","へ"], ans:1,
    ex:"「にほんのかいしゃいん」= 'karyawan perusahaan Jepang'. の menunjukkan hubungan/asal." },
  { cat:"no", pola:"Pola 4: ～の～", topic:"Partikel の",
    dlg:[{s:"A",t:"あれは　だれ（___）かさですか。"},{s:"B",t:"やまださんのです。"}],
    ch:["の","が","を","は"], ans:0,
    ex:"「だれのかさ」= 'payung siapa'. 「の」menunjukkan kepemilikan." },

  // ===== POLA 5: ～もです =====
  { cat:"mo", pola:"Pola 5: ～も～です", topic:"Partikel も",
    dlg:[{s:"A",t:"わたしは　にほんじんです。"},{s:"B",t:"わたし（___）　にほんじんです。"}],
    ch:["は","も","が","と"], ans:1,
    ex:"「も」= 'juga'. Menyatakan kesamaan dengan hal sebelumnya. 'Saya juga orang Jepang'." },
  { cat:"mo", pola:"Pola 5: ～も～です", topic:"Partikel も",
    solo:"コーヒーを　のみます。こうちゃ（___）　のみます。",
    ch:["は","が","を","も"], ans:3,
    ex:"「も」menggantikan partikel lain untuk menyatakan 'juga'. 'Minum kopi, minum teh juga'." },
  { cat:"mo", pola:"Pola 5: ～も～です", topic:"Partikel も",
    dlg:[{s:"A",t:"スミスさんは　アメリカじんですか。"},{s:"B",t:"はい、ジョンさん（___）アメリカじんです。"}],
    ch:["は","が","も","の"], ans:2,
    ex:"「も」= 'juga'. 'Smith orang Amerika. John juga orang Amerika'." },

  // ===== POLA 6: ～さいです =====
  { cat:"nenrei", pola:"Pola 6: ～さいです", topic:"Usia",
    dlg:[{s:"A",t:"おいくつですか。"},{s:"B",t:"にじゅうさん（___）です。"}],
    ch:["ねん","さい","まい","かい"], ans:1,
    ex:"「〜さい」= satuan usia. 「にじゅうさんさい」= '23 tahun'." },
  { cat:"nenrei", pola:"Pola 6: ～さいです", topic:"Usia",
    solo:"あのこは　なん（___）ですか。",
    ch:["さつ","さい","ほん","まい"], ans:1,
    ex:"「なんさいですか」= 'Berapa umurnya?' Menanyakan usia menggunakan「さい」." },
  { cat:"nenrei", pola:"Pola 6: ～さいです", topic:"Usia",
    dlg:[{s:"A",t:"おかあさんは　なんさいですか。"},{s:"B",t:"ごじゅう（___）です。"}],
    ch:["さい","えん","ほん","かい"], ans:0,
    ex:"「ごじゅうさい」= '50 tahun'. Satuan usia selalu 「〜さい」." },

  // ===== POLA 7: これ/それ/あれはです =====
  { cat:"kosoado", pola:"Pola 7: これ/それ/あれ", topic:"Ko-So-A-Do",
    dlg:[{s:"A",t:"（___）は　なんですか。"},{s:"B",t:"わたしの　くるまです。"}],
    ch:["ここ","この","これ","こちら"], ans:2,
    ex:"「これ」digunakan untuk benda dekat pembicara. 'Ini apa?' — menunjuk benda." },
  { cat:"kosoado", pola:"Pola 7: これ/それ/あれ", topic:"Ko-So-A-Do",
    solo:"（___）は　えんぴつです。（___）は　けしゴムです。",
    ch:["これ、それ","この、その","ここ、そこ","こちら、そちら"], ans:0,
    ex:"「これ」dan「それ」= kata ganti benda. 'Ini pensil. Itu penghapus'." },
  { cat:"kosoado", pola:"Pola 7: これ/それ/あれ", topic:"Ko-So-A-Do",
    dlg:[{s:"A",t:"（___）のたてものは　なんですか。"},{s:"B",t:"びょういんです。"}],
    ch:["あれ","あそこ","あの","あちら"], ans:0,
    ex:"「あれ」= benda jauh dari keduanya. 'Gedung itu apa?' (jauh dari A dan B)." },

  // ===== POLA 8: それは〜ですか、〜ですか =====
  { cat:"sentaku", pola:"Pola 8: 〜ですか、〜ですか", topic:"Pertanyaan Pilihan",
    dlg:[{s:"A",t:"それは　コーヒー（___）、こうちゃ（___）。"},{s:"B",t:"こうちゃです。"}],
    ch:["ですか、ですか","か、か","ですか？、ですか？","は、は"], ans:0,
    ex:"「〜ですか、〜ですか」= pertanyaan pilihan. 'Itu kopi atau teh?'" },
  { cat:"sentaku", pola:"Pola 8: 〜ですか、〜ですか", topic:"Pertanyaan Pilihan",
    solo:"あした　いきますか、（___）か。",
    ch:["いきません","いきましょう","いきます","いきました"], ans:0,
    ex:"Pertanyaan pilihan: 「いきますか、いきませんか」= 'Pergi atau tidak?'" },
  { cat:"sentaku", pola:"Pola 8: 〜ですか、〜ですか", topic:"Pertanyaan Pilihan",
    dlg:[{s:"A",t:"おちゃに　しますか、（___）に　しますか。"},{s:"B",t:"コーヒーを　おねがいします。"}],
    ch:["コーヒー","ジュース","みず","ぎゅうにゅう"], ans:0,
    ex:"「〜か、〜か」memberikan dua pilihan. Jawaban B memilih kopi." },

  // ===== POLA 9: この/その/あの =====
  { cat:"kosoado", pola:"Pola 9: この/その/あの", topic:"Ko-So-A-Do",
    solo:"（___）ほんは　たかかったです。",
    ch:["これ","ここ","この","こ"], ans:2,
    ex:"「この」= kata penentu (modifikasi kata benda berikutnya). 「このほん」= 'buku ini'." },
  { cat:"kosoado", pola:"Pola 9: この/その/あの", topic:"Ko-So-A-Do",
    dlg:[{s:"A",t:"（___）かたは　どなたですか。"},{s:"B",t:"やまだせんせいです。"}],
    ch:["あれ","あそこ","あの","あちら"], ans:2,
    ex:"「あの」= kata penentu untuk hal jauh. 「あのかた」= 'orang itu (jauh)'." },
  { cat:"kosoado", pola:"Pola 9: この/その/あの", topic:"Ko-So-A-Do",
    solo:"（___）くつは　だれのですか。",
    ch:["その","それ","そこ","そちら"], ans:0,
    ex:"「その」modifikasi kata benda. 「そのくつ」= 'sepatu itu'. Berbeda dari「それ」(kata ganti)." },

  // ===== POLA 10: ここ/そこ/あそこ =====
  { cat:"kosoado", pola:"Pola 10: ここ/そこ/あそこ", topic:"Tempat Ko-So-A-Do",
    dlg:[{s:"A",t:"トイレは　どこですか。"},{s:"B",t:"（___）です。"}],
    ch:["あれ","あの","あそこ","あちら"], ans:2,
    ex:"「あそこ」= tempat yang jauh. 'Di sana (jauh)'. 「あちら」lebih sopan untuk orang." },
  { cat:"kosoado", pola:"Pola 10: ここ/そこ/あそこ", topic:"Tempat Ko-So-A-Do",
    solo:"（___）は　どこですか。このへやです。",
    ch:["ここ","そこ","あそこ","どこ"], ans:0,
    ex:"「ここ」= tempat dekat pembicara. 'Di sini, di ruangan ini'." },
  { cat:"kosoado", pola:"Pola 10: ここ/そこ/あそこ", topic:"Tempat Ko-So-A-Do",
    dlg:[{s:"A",t:"ゆうびんきょくは（___）ですか。"},{s:"B",t:"えきのとなりです。"}],
    ch:["どれ","どの","どこ","どちら"], ans:2,
    ex:"「どこですか」= 'Di mana?' Bertanya tentang lokasi/tempat." },

  // ===== POLA 11: ～はここです =====
  { cat:"ichi", pola:"Pola 11: ～はここです", topic:"Menyatakan Lokasi",
    solo:"じむしょ（___）　あそこです。",
    ch:["が","も","は","の"], ans:2,
    ex:"「〜は　あそこです」= 'Kantor ada di sana'. Topik ditandai「は」, lokasi ditunjukkan「ここ/そこ/あそこ」." },
  { cat:"ichi", pola:"Pola 11: ～はここです", topic:"Menyatakan Lokasi",
    dlg:[{s:"A",t:"かいぎしつは　どこですか。"},{s:"B",t:"かいぎしつ（___）　そこです。"}],
    ch:["が","は","を","に"], ans:1,
    ex:"「かいぎしつは　そこです」= 'Ruang rapat ada di situ'. Topik pakai「は」." },
  { cat:"ichi", pola:"Pola 11: ～はここです", topic:"Menyatakan Lokasi",
    solo:"レストランは（___）です。にかいです。",
    ch:["どこ","どちら","どれ","どの"], ans:0,
    ex:"「どこですか」= 'Di mana?' Menjawab dengan lokasi spesifik." },

  // ===== POLA 12: ～はに あります/います =====
  { cat:"ari_imas", pola:"Pola 12: ～はにあります/います", topic:"Keberadaan",
    dlg:[{s:"A",t:"やまださんは　どこに　いますか。"},{s:"B",t:"かいぎしつ（___）います。"}],
    ch:["へ","で","に","が"], ans:2,
    ex:"「〜に　います」= 'ada di...' Partikel「に」menunjukkan tempat keberadaan orang/benda." },
  { cat:"ari_imas", pola:"Pola 12: ～はにあります/います", topic:"Keberadaan",
    solo:"じしょは　つくえのうえ（___）あります。",
    ch:["で","に","へ","が"], ans:1,
    ex:"「〜に　あります」= 'ada di...' Partikel「に」+ あります untuk benda mati." },
  { cat:"ari_imas", pola:"Pola 12: ～はにあります/います", topic:"Keberadaan",
    dlg:[{s:"A",t:"ねこは（___）いますか。"},{s:"B",t:"にわにいます。"}],
    ch:["どこに","なにに","だれに","いつに"], ans:0,
    ex:"「どこに　いますか」= 'Ada di mana?' Kata tanya tempat untuk makhluk hidup." },

  // ===== POLA 13: こちら/そちら/あちら =====
  { cat:"kosoado", pola:"Pola 13: こちら/そちら/あちら", topic:"Ko-So-A-Do Sopan",
    dlg:[{s:"A",t:"ごあんないします。レストランは（___）です。"},{s:"B",t:"ありがとうございます。"}],
    ch:["あそこ","あれ","あちら","あの"], ans:2,
    ex:"「あちら」= bentuk sopan dari「あそこ」. Digunakan saat mengarahkan orang dengan sopan." },
  { cat:"kosoado", pola:"Pola 13: こちら/そちら/あちら", topic:"Ko-So-A-Do Sopan",
    solo:"はじめまして。わたしは　たなかです。（___）は？",
    ch:["そちら","そこ","それ","その"], ans:0,
    ex:"「そちらは？」= 'Bagaimana dengan Anda?' Bentuk sopan saat berkenalan." },
  { cat:"kosoado", pola:"Pola 13: こちら/そちら/あちら", topic:"Ko-So-A-Do Sopan",
    dlg:[{s:"A",t:"えきは（___）ですか。"},{s:"B",t:"（___）です。みぎに　まがってください。"}],
    ch:["どちら、こちら","どこ、ここ","どれ、これ","どの、この"], ans:0,
    ex:"「どちら」= bentuk sopan「どこ」. 「こちら」= arah ke sini (sopan)." },

  // ===== POLA 14: ～の～です (negara/perusahaan) =====
  { cat:"no", pola:"Pola 14: ～の～ (asal)", topic:"Partikel の",
    solo:"これは　にほん（___）くるまです。",
    ch:["で","の","に","が"], ans:1,
    ex:"「にほんのくるま」= 'mobil (buatan) Jepang'. の menunjukkan asal/asosiasi." },
  { cat:"no", pola:"Pola 14: ～の～ (asal)", topic:"Partikel の",
    dlg:[{s:"A",t:"そのかばんは　どこ（___）ですか。"},{s:"B",t:"イタリアのです。"}],
    ch:["の","が","を","で"], ans:0,
    ex:"「どこのですか」= 'dari mana?' Menanyakan asal produk dengan「の」." },
  { cat:"no", pola:"Pola 14: ～の～ (asal)", topic:"Partikel の",
    solo:"ソニー（___）カメラは　ゆうめいです。",
    ch:["に","が","の","を"], ans:2,
    ex:"「ソニーのカメラ」= 'kamera Sony'. の menunjukkan merek/perusahaan asal." },

  // ===== POLA 15: ～えんです =====
  { cat:"nedan", pola:"Pola 15: ～えんです", topic:"Harga",
    dlg:[{s:"A",t:"このほんは　いくらですか。"},{s:"B",t:"さんぜんえん（___）。"}],
    ch:["があります","をします","です","にあります"], ans:2,
    ex:"「〜えんです」= 'harganya ~ yen'. Menyatakan harga menggunakan です." },
  { cat:"nedan", pola:"Pola 15: ～えんです", topic:"Harga",
    solo:"このコーヒーは　ごひゃく（___）です。",
    ch:["さい","えん","ほん","まい"], ans:1,
    ex:"「〜えん」= satuan mata uang yen. 「ごひゃくえん」= '500 yen'." },
  { cat:"nedan", pola:"Pola 15: ～えんです", topic:"Harga",
    dlg:[{s:"A",t:"このケーキは　（___）ですか。"},{s:"B",t:"ひゃくごじゅうえんです。"}],
    ch:["どう","いくら","なんじ","どんな"], ans:1,
    ex:"「いくらですか」= 'Berapa harganya?' Menanyakan harga." },

  // ===== POLA 16: いまKWです =====
  { cat:"jikan", pola:"Pola 16: いまKWです", topic:"Waktu",
    dlg:[{s:"A",t:"いまは　なんじですか。"},{s:"B",t:"（___）です。"}],
    ch:["ごぜんくじ","きのう","らいしゅう","げつようび"], ans:0,
    ex:"「いまは　なんじですか」= 'Sekarang jam berapa?' Menjawab dengan waktu." },
  { cat:"jikan", pola:"Pola 16: いまKWです", topic:"Waktu",
    solo:"いまは　ごぜん（___）じはんです。",
    ch:["さん","みっつ","みっか","さんさい"], ans:0,
    ex:"「ごぜんさんじはん」= 'jam 3:30 pagi'. 「さん」untuk angka dalam jam." },
  { cat:"jikan", pola:"Pola 16: いまKWです", topic:"Waktu",
    dlg:[{s:"A",t:"（___）は　なんじですか。"},{s:"B",t:"ごごにじです。"}],
    ch:["いくら","いつ","いま","いかが"], ans:2,
    ex:"「いま」= sekarang. 「いまはなんじですか」= 'Sekarang jam berapa?'" },

  // ===== POLA 17: ～はKW1からKW2までです =====
  { cat:"kara_made", pola:"Pola 17: ～からまでです", topic:"Rentang Waktu",
    solo:"ぎんこうは　くじ（___）　ごじ（___）です。",
    ch:["に、に","から、まで","まで、から","に、まで"], ans:1,
    ex:"「から〜まで」= 'dari ... sampai ...'. 「くじから　ごじまで」= 'dari jam 9 sampai jam 5'." },
  { cat:"kara_made", pola:"Pola 17: ～からまでです", topic:"Rentang Waktu",
    dlg:[{s:"A",t:"やすみは　いつからいつまでですか。"},{s:"B",t:"もくようび（___）　にちようび（___）です。"}],
    ch:["から、まで","に、に","まで、から","へ、へ"], ans:0,
    ex:"「もくようびから　にちようびまで」= 'dari Kamis sampai Minggu'." },
  { cat:"kara_made", pola:"Pola 17: ～からまでです", topic:"Rentang Waktu",
    solo:"このしごとは　なんじ（___）　なんじ（___）ですか。",
    ch:["に、まで","から、まで","へ、まで","で、まで"], ans:1,
    ex:"「なんじから　なんじまでですか」= 'Dari jam berapa sampai jam berapa?'" },

  // ===== POLA 18: ～にKK =====
  { cat:"jikan_ni", pola:"Pola 18: ～に KK", topic:"Partikel に (waktu)",
    solo:"わたしは　まいあさ　しちじ（___）　おきます。",
    ch:["で","へ","に","を"], ans:2,
    ex:"「〜に　おきます」= 'bangun jam...'. Partikel「に」menunjukkan waktu spesifik untuk beraktivitas." },
  { cat:"jikan_ni", pola:"Pola 18: ～に KK", topic:"Partikel に (waktu)",
    dlg:[{s:"A",t:"いつ　にほんへ　きましたか。"},{s:"B",t:"ことし　さんがつ（___）　きました。"}],
    ch:["に","で","を","が"], ans:0,
    ex:"「さんがつに　きました」= 'datang di bulan Maret'. Waktu spesifik (bulan, hari, jam) pakai「に」." },
  { cat:"jikan_ni", pola:"Pola 18: ～に KK", topic:"Partikel に (waktu)",
    solo:"にちようび（___）テニスを　します。",
    ch:["は","で","に","が"], ans:2,
    ex:"「にちようびに」= 'pada hari Minggu'. Hari dalam seminggu pakai「に」." },

  // ===== POLA 19: ～からまでKK =====
  { cat:"kara_made", pola:"Pola 19: ～からまでKK", topic:"Rentang Waktu + Aksi",
    solo:"くじ（___）　ごじ（___）　しごとを　します。",
    ch:["まで、から","に、に","から、まで","へ、まで"], ans:2,
    ex:"「くじから　ごじまで　しごとをします」= 'Kerja dari jam 9 sampai jam 5'." },
  { cat:"kara_made", pola:"Pola 19: ～からまでKK", topic:"Rentang Waktu + Aksi",
    dlg:[{s:"A",t:"としょかんは　なんじから　なんじ（___）　あいていますか。"},{s:"B",t:"くじから　ごじまでです。"}],
    ch:["まで","から","に","で"], ans:0,
    ex:"「なんじまであいていますか」= 'Buka sampai jam berapa?'" },
  { cat:"kara_made", pola:"Pola 19: ～からまでKK", topic:"Rentang Waktu + Aksi",
    solo:"とうきょう（___）おおさか（___）　しんかんせんで　いきます。",
    ch:["に、まで","から、まで","へ、まで","まで、から"], ans:1,
    ex:"「から〜まで」juga bisa untuk rentang tempat. 'Dari Tokyo sampai Osaka'." },

  // ===== POLA 20: KK ます/ません/ました/ませんでした =====
  { cat:"masu", pola:"Pola 20: KK ます活用", topic:"Bentuk Kata Kerja",
    dlg:[{s:"A",t:"きのう　テレビを　みましたか。"},{s:"B",t:"いいえ、（___）。"}],
    ch:["みました","みません","みませんでした","みましょう"], ans:2,
    ex:"「みませんでした」= 'tidak menonton (lampau)'. Negatif lampau: ～ませんでした." },
  { cat:"masu", pola:"Pola 20: KK ます活用", topic:"Bentuk Kata Kerja",
    solo:"あした　がっこうへ　（___）。",
    ch:["いきません","いきます","いきました","いきませんでした"], ans:1,
    ex:"「いきます」= 'akan pergi (masa depan/sekarang)'. Bentuk positif non-lampau." },
  { cat:"masu", pola:"Pola 20: KK ます活用", topic:"Bentuk Kata Kerja",
    dlg:[{s:"A",t:"まいあさ　なにを　たべますか。"},{s:"B",t:"パンを　（___）。"}],
    ch:["たべます","たべました","たべません","たべましょう"], ans:0,
    ex:"Pertanyaan tentang kebiasaan (まいあさ) → jawab dengan bentuk non-lampau 「たべます」." },

  // ===== POLA 21: ～へいきます/きます/かえります =====
  { cat:"movement", pola:"Pola 21: ～へいきます/きます/かえります", topic:"Gerakan",
    solo:"わたしは　まいにち　がっこう（___）　いきます。",
    ch:["で","を","へ","が"], ans:2,
    ex:"「〜へ　いきます」= 'pergi ke...'. 「へ」menunjukkan arah tujuan." },
  { cat:"movement", pola:"Pola 21: ～へいきます/きます/かえります", topic:"Gerakan",
    dlg:[{s:"A",t:"どこへ　いきますか。"},{s:"B",t:"スーパー（___）　かいものに　いきます。"}],
    ch:["で","を","に","へ"], ans:3,
    ex:"「スーパーへ　いきます」= 'pergi ke supermarket'. 「へ」menunjukkan tujuan." },
  { cat:"movement", pola:"Pola 21: ～へいきます/きます/かえります", topic:"Gerakan",
    solo:"しごとの　あとで　うち（___）　かえります。",
    ch:["を","へ","で","が"], ans:1,
    ex:"「うちへ　かえります」= 'pulang ke rumah'. 「かえります」selalu dengan「へ」atau「に」." },

  // ===== POLA 22: ～で～へ (kendaraan) =====
  { cat:"movement", pola:"Pola 22: ～でへいきます", topic:"Kendaraan",
    solo:"わたしは　バス（___）　えき（___）　いきます。",
    ch:["で、へ","に、で","へ、に","を、で"], ans:0,
    ex:"「バスで　えきへ　いきます」= 'naik bus pergi ke stasiun'. で = alat, へ = tujuan." },
  { cat:"movement", pola:"Pola 22: ～でへいきます", topic:"Kendaraan",
    dlg:[{s:"A",t:"がっこうまで　なんで　きますか。"},{s:"B",t:"じてんしゃ（___）　きます。"}],
    ch:["へ","で","に","を"], ans:1,
    ex:"「じてんしゃで」= 'dengan sepeda'. Partikel「で」menunjukkan alat/kendaraan." },
  { cat:"movement", pola:"Pola 22: ～でへいきます", topic:"Kendaraan",
    solo:"くうこう（___）　でんしゃ（___）　いきます。",
    ch:["を、で","へ、で","に、に","で、へ"], ans:1,
    ex:"「くうこうへ　でんしゃで　いきます」= 'pergi ke bandara naik kereta'. へ=tujuan, で=kendaraan." },

  // ===== POLA 23: ～と～へ (bersama) =====
  { cat:"to", pola:"Pola 23: ～と～へいきます", topic:"Bersama",
    solo:"わたしは　ともだち（___）　えいがを　みに　いきます。",
    ch:["に","で","と","が"], ans:2,
    ex:"「ともだちと」= 'bersama teman'. 「と」menunjukkan teman/orang yang menemani." },
  { cat:"to", pola:"Pola 23: ～と～へいきます", topic:"Bersama",
    dlg:[{s:"A",t:"だれと　りょこうしましたか。"},{s:"B",t:"かぞく（___）　いきました。"}],
    ch:["に","で","と","が"], ans:2,
    ex:"「かぞくと　いきました」= 'pergi bersama keluarga'. Menemani seseorang = 「と」." },
  { cat:"to", pola:"Pola 23: ～と～へいきます", topic:"Bersama",
    solo:"きのう　ひとり（___）　いきました。だれ（___）　いきませんでした。",
    ch:["で、も","と、とも","に、も","が、が"], ans:1,
    ex:"「ひとりで」= 'sendirian'. 「だれとも　いきませんでした」= 'tidak pergi bersama siapapun'." },

  // ===== POLA 24: ～をKK (transitif) =====
  { cat:"wo", pola:"Pola 24: ～をKK", topic:"Partikel を",
    solo:"まいあさ　しんぶん（___）　よみます。",
    ch:["が","に","を","は"], ans:2,
    ex:"「を」menandai objek kata kerja transitif. 「しんぶんをよむ」= 'membaca koran'." },
  { cat:"wo", pola:"Pola 24: ～をKK", topic:"Partikel を",
    dlg:[{s:"A",t:"なに（___）　かいましたか。"},{s:"B",t:"くつを　かいました。"}],
    ch:["が","を","は","に"], ans:1,
    ex:"「なにをかいましたか」= 'Membeli apa?' 「を」menandai objek 「かいます」." },
  { cat:"wo", pola:"Pola 24: ～をKK", topic:"Partikel を",
    solo:"こうえんで　おんがく（___）　ききます。",
    ch:["に","で","を","が"], ans:2,
    ex:"「おんがくをきく」= 'mendengarkan musik'. 「を」= objek kata kerja transitif." },

  // ===== POLA 25: ～をします =====
  { cat:"wo_shimasu", pola:"Pola 25: ～をします", topic:"〜をします",
    solo:"まいにち　うんどう（___）　します。",
    ch:["が","に","を","で"], ans:2,
    ex:"「〜をします」= 'melakukan ~'. Nomina + をします = aktivitas." },
  { cat:"wo_shimasu", pola:"Pola 25: ～をします", topic:"〜をします",
    dlg:[{s:"A",t:"しゅみは　なんですか。"},{s:"B",t:"りょうり（___）　します。"}],
    ch:["に","を","が","は"], ans:1,
    ex:"「りょうりをします」= 'memasak'. 趣味 (hobi) sering dinyatakan dengan 〜をします." },
  { cat:"wo_shimasu", pola:"Pola 25: ～をします", topic:"〜をします",
    solo:"にちようびに　テニス（___）　します。",
    ch:["が","に","を","は"], ans:2,
    ex:"「テニスをします」= 'bermain tenis'. Olahraga + を + します." },

  // ===== POLA 26: なにをしますか =====
  { cat:"nani", pola:"Pola 26: なにをしますか", topic:"Kata Tanya",
    dlg:[{s:"A",t:"にちようびに　（___）しますか。"},{s:"B",t:"えいがをみます。"}],
    ch:["どこで","なにを","なんで","いつ"], ans:1,
    ex:"「なにをしますか」= 'Akan melakukan apa?'. 答え(jawaban) pakai「〜をします」." },
  { cat:"nani", pola:"Pola 26: なにをしますか", topic:"Kata Tanya",
    solo:"あなたは　まいあさ（___）　たべますか。",
    ch:["どこを","なにを","なんで","いつを"], ans:1,
    ex:"「なにをたべますか」= 'Makan apa?'. 「なに + を + 食べます」." },
  { cat:"nani", pola:"Pola 26: なにをしますか", topic:"Kata Tanya",
    dlg:[{s:"A",t:"パーティーで（___）しましたか。"},{s:"B",t:"うたを　うたいました。"}],
    ch:["なにを","どこを","なんに","だれを"], ans:0,
    ex:"「なにをしましたか」= 'Melakukan apa?'. Jawaban berupa aktivitas dengan「を」." },

  // ===== POLA 27: なん vs なに =====
  { cat:"nan_nani", pola:"Pola 27: なん vs なに", topic:"Kata Tanya",
    dlg:[{s:"A",t:"これは（___）ですか。"},{s:"B",t:"ほんです。"}],
    ch:["なに","なん","どれ","どの"], ans:1,
    ex:"「なんですか」= dipakai sebelum「です/で/の/だ」. 「これはなんですか」= 'Ini apa?'" },
  { cat:"nan_nani", pola:"Pola 27: なん vs なに", topic:"Kata Tanya",
    solo:"（___）を　かいましたか。",
    ch:["なん","なに","どれ","どの"], ans:1,
    ex:"「なに」dipakai sebelum partikel selain で/の/だ. 「なにをかいましたか」= 'Membeli apa?'" },
  { cat:"nan_nani", pola:"Pola 27: なん vs なに", topic:"Kata Tanya",
    dlg:[{s:"A",t:"これは（___）語ですか。"},{s:"B",t:"にほんごです。"}],
    ch:["なに","なん","どの","どれ"], ans:1,
    ex:"「なんご」→ なん dipakai sebelum「語(ご)」yang diawali konsonan. 「なんごですか」= '〜bahasa apa?'" },

  // ===== POLA 28: ～でKK (tempat) =====
  { cat:"de_basho", pola:"Pola 28: ～でKK (tempat)", topic:"Partikel で",
    solo:"わたしは　としょかん（___）　べんきょうします。",
    ch:["に","で","へ","を"], ans:1,
    ex:"「〜で　べんきょうします」= 'belajar di...'. 「で」menunjukkan tempat beraktivitas." },
  { cat:"de_basho", pola:"Pola 28: ～でKK (tempat)", topic:"Partikel で",
    dlg:[{s:"A",t:"どこで　ひるごはんを　たべますか。"},{s:"B",t:"しょくどう（___）たべます。"}],
    ch:["に","で","へ","を"], ans:1,
    ex:"「しょくどうで　たべます」= 'makan di kantin'. 「で」= tempat aktivitas." },
  { cat:"de_basho", pola:"Pola 28: ～でKK (tempat)", topic:"Partikel で",
    solo:"とうきょう（___）　おみやげを　かいました。",
    ch:["へ","に","で","が"], ans:2,
    ex:"「とうきょうで　かいました」= 'membeli di Tokyo'. 「で」= tempat terjadinya aksi." },

  // ===== POLA 29: ～ませんか (ajakan) =====
  { cat:"masenka", pola:"Pola 29: ～ませんか", topic:"Ajakan",
    dlg:[{s:"A",t:"いっしょに　えいがを　み（___）。"},{s:"B",t:"ええ、いいですね。"}],
    ch:["ましょう","ませんか","ません","ました"], ans:1,
    ex:"「〜ませんか」= ajakan halus. 'Bagaimana kalau menonton film bersama?'" },
  { cat:"masenka", pola:"Pola 29: ～ませんか", topic:"Ajakan",
    solo:"あした　こうえんへ　さんぽし（___）。",
    ch:["ましょう","ませんか","ました","ません"], ans:1,
    ex:"「〜ませんか」= mengajak dengan sopan. 'Bagaimana kalau jalan-jalan ke taman besok?'" },
  { cat:"masenka", pola:"Pola 29: ～ませんか", topic:"Ajakan",
    dlg:[{s:"A",t:"いっしょに　ひるごはんを　たべ（___）。"},{s:"B",t:"いいですね、たべましょう。"}],
    ch:["ません","ませんか","ました","ましょう"], ans:1,
    ex:"「たべませんか」= ajakan. Lawan bicara menyetujui dengan「たべましょう」." },

  // ===== POLA 30: ～ましょう =====
  { cat:"mashou", pola:"Pola 30: ～ましょう", topic:"Ayo Kita",
    dlg:[{s:"A",t:"つかれましたね。すこし　やすみ（___）。"},{s:"B",t:"そうですね。"}],
    ch:["ませんか","ましょう","ません","ました"], ans:1,
    ex:"「〜ましょう」= 'ayo kita...'. Mengajak bersama atau mengungkapkan niat bersama." },
  { cat:"mashou", pola:"Pola 30: ～ましょう", topic:"Ayo Kita",
    solo:"もう　おそいですから、かえり（___）。",
    ch:["ました","ません","ましょう","ませんか"], ans:2,
    ex:"「かえりましょう」= 'ayo kita pulang'. 「ましょう」= ajakan/keputusan bersama." },
  { cat:"mashou", pola:"Pola 30: ～ましょう", topic:"Ayo Kita",
    dlg:[{s:"A",t:"つぎの　えきで　おり（___）。"},{s:"B",t:"はい、そうしましょう。"}],
    ch:["ませんか","ましょう","ません","ました"], ans:1,
    ex:"「おりましょう」= 'ayo turun'. Lawan bicara setuju dengan「そうしましょう」." },

  // ===== POLA 31: ～で (alat/cara) =====
  { cat:"de_cara", pola:"Pola 31: ～で (alat/cara)", topic:"Partikel で",
    solo:"はし（___）　ごはんを　たべます。",
    ch:["に","を","で","は"], ans:2,
    ex:"「はしで　たべます」= 'makan dengan sumpit'. 「で」menunjukkan alat yang digunakan." },
  { cat:"de_cara", pola:"Pola 31: ～で (alat/cara)", topic:"Partikel で",
    dlg:[{s:"A",t:"なに（___）　かきましたか。"},{s:"B",t:"えんぴつで　かきました。"}],
    ch:["を","で","に","が"], ans:0,
    ex:"「なにで　かきましたか」= 'Menulis dengan apa?' Alat = 「で」." },
  { cat:"de_cara", pola:"Pola 31: ～で (alat/cara)", topic:"Partikel で",
    solo:"にほんごの　クラスでは　にほんご（___）　はなします。",
    ch:["に","が","で","は"], ans:2,
    ex:"「にほんごで　はなします」= 'berbicara dalam bahasa Jepang'. Bahasa = alat = 「で」." },

  // ===== POLA 32: ～語でですです (terjemahan) =====
  { cat:"terjemahan", pola:"Pola 32: ～語で～です", topic:"Terjemahan",
    dlg:[{s:"A",t:"「ありがとう」は　インドネシアご（___）　なんですか。"},{s:"B",t:"「テリマカシ」です。"}],
    ch:["は","に","で","が"], ans:2,
    ex:"「〜語で　なんですか」= '...dalam bahasa ~, apa?'. 「で」menunjukkan bahasa sebagai alat." },
  { cat:"terjemahan", pola:"Pola 32: ～語で～です", topic:"Terjemahan",
    solo:"「おはようございます」は　えいご（___）　「Good morning」です。",
    ch:["に","は","の","で"], ans:3,
    ex:"「えいごで　〜です」= 'Dalam bahasa Inggris adalah...'. 「で」= menggunakan bahasa itu." },
  { cat:"terjemahan", pola:"Pola 32: ～語で～です", topic:"Terjemahan",
    dlg:[{s:"A",t:"「さようなら」は　にほんご（___）なんですか。"},{s:"B",t:"「Sampai jumpa」です。"}],
    ch:["が","で","を","の"], ans:1,
    ex:"「にほんごで　なんですか」= 'Dalam bahasa Jepang, apa?' 「で」= bahasa sebagai medium." },

  // ===== POLA 33: ～にをあげます =====
  { cat:"ageru_morau", pola:"Pola 33: ～にをあげます", topic:"Memberi",
    dlg:[{s:"A",t:"ワットさんは　マリアさん（___）　はなを　あげました。"},{s:"B",t:"そうですか。"}],
    ch:["が","に","を","で"], ans:1,
    ex:"「〔penerima〕に　〜をあげます」= 'memberikan ~ kepada...'. Penerima ditandai「に」." },
  { cat:"ageru_morau", pola:"Pola 33: ～にをあげます", topic:"Memberi",
    solo:"わたしは　せんせい（___）　プレゼントを　あげます。",
    ch:["が","に","で","を"], ans:1,
    ex:"「せんせいに　あげます」= 'memberikan kepada guru'. Penerima + に + を + あげます." },
  { cat:"ageru_morau", pola:"Pola 33: ～にをあげます", topic:"Memberi",
    dlg:[{s:"A",t:"たなかさんに　なに（___）　あげましたか。"},{s:"B",t:"ほんをあげました。"}],
    ch:["に","で","を","が"], ans:2,
    ex:"「なにをあげましたか」= 'Memberikan apa?'. 「を」menandai benda yang diberikan." },

  // ===== POLA 34: ～にをもらいます =====
  { cat:"ageru_morau", pola:"Pola 34: ～にをもらいます", topic:"Menerima",
    dlg:[{s:"A",t:"このネクタイは　すてきですね。"},{s:"B",t:"ありがとう。マリアさん（___）　もらいました。"}],
    ch:["で","を","に","が"], ans:2,
    ex:"「〔pemberi〕に　〜をもらいます」= 'menerima dari...'. Pemberi ditandai「に」." },
  { cat:"ageru_morau", pola:"Pola 34: ～にをもらいます", topic:"Menerima",
    solo:"わたしは　ははおや（___）　てがみ（___）　もらいました。",
    ch:["に、を","を、に","が、を","に、が"], ans:0,
    ex:"「ははおやに　てがみを　もらいました」= 'menerima surat dari ibu'. に=pemberi, を=benda." },
  { cat:"ageru_morau", pola:"Pola 34: ～にをもらいます", topic:"Menerima",
    dlg:[{s:"A",t:"たんじょうびに　だれ（___）　プレゼント（___）もらいましたか。"},{s:"B",t:"ともだちにもらいました。"}],
    ch:["に、を","を、に","が、を","は、が"], ans:0,
    ex:"「だれに〜をもらいましたか」= 'Menerima dari siapa?'. に=pemberi, を=benda yang diterima." },

  // ===== POLA 35: もう～ました =====
  { cat:"mou", pola:"Pola 35: もう～ました", topic:"Sudah",
    dlg:[{s:"A",t:"もう　しゅくだいを　しましたか。"},{s:"B",t:"はい、（___）。"}],
    ch:["しません","しました","します","していません"], ans:1,
    ex:"「もう〜ました」= 'sudah melakukan'. 「はい、しました」= 'Ya, sudah'." },
  { cat:"mou", pola:"Pola 35: もう～ました", topic:"Sudah",
    solo:"（___）　ひるごはんを　たべましたか。",
    ch:["まだ","もう","まで","また"], ans:1,
    ex:"「もう　たべましたか」= 'Sudah makan siang?'. 「もう」= already/sudah." },
  { cat:"mou", pola:"Pola 35: もう～ました", topic:"Sudah",
    dlg:[{s:"A",t:"もう　てがみを　かきましたか。"},{s:"B",t:"いいえ、（___）　かいていません。"}],
    ch:["もう","まだ","また","まず"], ans:1,
    ex:"「まだ〜ていません」= 'belum...'. Kebalikan dari「もう〜ました」." },

  // ===== POLA 36: KS な/い + です =====
  { cat:"keiyoshi", pola:"Pola 36: KS です", topic:"Kata Sifat",
    solo:"このまちは　（___）です。",
    ch:["にぎやかな","にぎやか","にぎやかく","にぎやかの"], ans:1,
    ex:"Kata sifat な sebelum「です」tidak perlu「な」. Cukup「にぎやかです」= 'ramai'." },
  { cat:"keiyoshi", pola:"Pola 36: KS です", topic:"Kata Sifat",
    dlg:[{s:"A",t:"このくつは　どうですか。"},{s:"B",t:"（___）です。でも　ちょっと　たかいです。"}],
    ch:["きれいな","きれい","きれいく","きれいで"], ans:1,
    ex:"「きれいです」= 'indah/cantik'. Kata sifat な + です: hilangkan「な」." },
  { cat:"keiyoshi", pola:"Pola 36: KS です", topic:"Kata Sifat",
    solo:"このもんだいは　（___）です。",
    ch:["むずかしいな","むずかしく","むずかしい","むずかしいの"], ans:2,
    ex:"「むずかしいです」= 'sulit'. Kata sifat い langsung + です tanpa perubahan." },

  // ===== POLA 37: KS な/い + KB =====
  { cat:"keiyoshi", pola:"Pola 37: KS + KB", topic:"Kata Sifat Modifikasi",
    solo:"さくらがっこうは　（___）　がっこうです。",
    ch:["ゆうめい","ゆうめいな","ゆうめいで","ゆうめいに"], ans:1,
    ex:"Kata sifat な sebelum kata benda wajib pakai「な」. 「ゆうめいながっこう」= 'sekolah terkenal'." },
  { cat:"keiyoshi", pola:"Pola 37: KS + KB", topic:"Kata Sifat Modifikasi",
    solo:"これは　（___）　えんぴつです。",
    ch:["あたらしいな","あたらしい","あたらしく","あたらしいの"], ans:1,
    ex:"Kata sifat い sebelum kata benda tetap dalam bentuk asli「〜い」. 「あたらしいえんぴつ」." },
  { cat:"keiyoshi", pola:"Pola 37: KS + KB", topic:"Kata Sifat Modifikasi",
    dlg:[{s:"A",t:"どんな　まちに　すみたいですか。"},{s:"B",t:"（___）まちに　すみたいです。"}],
    ch:["しずかな","しずか","しずかの","しずかく"], ans:0,
    ex:"「しずかな　まち」= 'kota yang tenang'. Kata sifat な + な + kata benda." },

  // ===== POLA 38: とても/あまり =====
  { cat:"fukushi", pola:"Pola 38: とても/あまり", topic:"Kata Keterangan",
    dlg:[{s:"A",t:"このえいがは　どうですか。"},{s:"B",t:"（___）　おもしろかったです。"}],
    ch:["あまり","ぜんぜん","とても","少し（negatif）"], ans:2,
    ex:"「とても」dipakai dengan kalimat positif. 'Sangat menarik'. 「あまり/ぜんぜん」untuk negatif." },
  { cat:"fukushi", pola:"Pola 38: とても/あまり", topic:"Kata Keterangan",
    dlg:[{s:"A",t:"にほんごは　どうですか。"},{s:"B",t:"（___）　むずかしく　ありません。"}],
    ch:["とても","あまり","たくさん","よく"], ans:1,
    ex:"「あまり〜ません」= 'tidak begitu...'. Selalu dengan bentuk negatif." },
  { cat:"fukushi", pola:"Pola 38: とても/あまり", topic:"Kata Keterangan",
    solo:"このすしは　（___）　おいしいです。",
    ch:["あまり","ぜんぜん","とても","すこし（negatif）"], ans:2,
    ex:"「とても　おいしい」= 'sangat enak'. Kalimat positif → 「とても」bukan「あまり」." },

  // ===== POLA 39: ～はどうですか =====
  { cat:"dou", pola:"Pola 39: ～はどうですか", topic:"Menanyakan Kesan",
    dlg:[{s:"A",t:"にほんの　たべもの（___）　どうですか。"},{s:"B",t:"おいしいです。"}],
    ch:["が","は","を","に"], ans:1,
    ex:"「〜はどうですか」= 'Bagaimana ~ (menurut Anda)?'. Topik pakai「は」." },
  { cat:"dou", pola:"Pola 39: ～はどうですか", topic:"Menanyakan Kesan",
    solo:"おちゃは（___）ですか。",
    ch:["どれ","どの","どこ","どう"], ans:3,
    ex:"「〜はどうですか」= menawarkan atau menanyakan kesan/pendapat tentang sesuatu." },
  { cat:"dou", pola:"Pola 39: ～はどうですか", topic:"Menanyakan Kesan",
    dlg:[{s:"A",t:"あたらしいしごとは（___）ですか。"},{s:"B",t:"たのしいですが、いそがしいです。"}],
    ch:["どう","どの","どれ","どこ"], ans:0,
    ex:"「しごとはどうですか」= 'Bagaimana pekerjaannya?' Kata tanya kesan = 「どう」." },

  // ===== POLA 40: ～はどんなKBですか =====
  { cat:"donna", pola:"Pola 40: ～はどんな～ですか", topic:"Menanyakan Sifat",
    dlg:[{s:"A",t:"やまださんは（___）ひとですか。"},{s:"B",t:"しんせつな　ひとです。"}],
    ch:["どの","どんな","どれ","どちら"], ans:1,
    ex:"「どんな〜ですか」= 'Seperti apa ~ itu?' Menanyakan sifat/karakter." },
  { cat:"donna", pola:"Pola 40: ～はどんな～ですか", topic:"Menanyakan Sifat",
    solo:"あなたの　まちは（___）まちですか。",
    ch:["どう","どこの","どんな","どの"], ans:2,
    ex:"「どんなまちですか」= 'Seperti apa kotanya?'. Menanyakan deskripsi/sifat." },
  { cat:"donna", pola:"Pola 40: ～はどんな～ですか", topic:"Menanyakan Sifat",
    dlg:[{s:"A",t:"さくらがっこうは（___）がっこうですか。"},{s:"B",t:"きれいで　おおきいがっこうです。"}],
    ch:["どれ","どんな","どの","どこの"], ans:1,
    ex:"「どんながっこうですか」= 'Seperti apa sekolahnya?'" },

  // ===== POLA 41: ～が、～ =====
  { cat:"ga_demo", pola:"Pola 41: ～が、～", topic:"Kontras/Tapi",
    solo:"このかばんは　すきです（___）、たかくて　かえません。",
    ch:["から","が","で","と"], ans:1,
    ex:"「〜が、〜」= 'Memang..., tapi...'. 「が」sebagai konjungsi kontras." },
  { cat:"ga_demo", pola:"Pola 41: ～が、～", topic:"Kontras/Tapi",
    dlg:[{s:"A",t:"このレストランは　やすい（___）、おいしくないです。"},{s:"B",t:"そうですか。"}],
    ch:["から","ので","が","けど"], ans:2,
    ex:"「〜が、〜」= kontras. 'Murah tapi tidak enak'. Dalam kalimat formal pakai「が」." },
  { cat:"ga_demo", pola:"Pola 41: ～が、～", topic:"Kontras/Tapi",
    solo:"にほんごは　おもしろい（___）、むずかしいです。",
    ch:["から","が","に","を"], ans:1,
    ex:"「おもしろいが、むずかしい」= 'menarik tapi sulit'. Kontras dengan「が」." },

  // ===== POLA 42: どれ =====
  { cat:"dore", pola:"Pola 42: どれ", topic:"Kata Tanya",
    dlg:[{s:"A",t:"やまださんの　かさは（___）ですか。"},{s:"B",t:"あの　あかいかさです。"}],
    ch:["どこ","どの","どれ","どんな"], ans:2,
    ex:"「どれ」= 'yang mana' (dari 3+ pilihan). Berdiri sendiri tanpa kata benda. 「どの〜」= modifikasi KB." },
  { cat:"dore", pola:"Pola 42: どれ", topic:"Kata Tanya",
    solo:"あなたの　くるまは（___）ですか。",
    ch:["どの","どれ","どこ","どちら"], ans:1,
    ex:"「どれですか」= 'Yang mana?' (memilih dari beberapa). 「どれ」tidak diikuti kata benda." },
  { cat:"dore", pola:"Pola 42: どれ", topic:"Kata Tanya",
    dlg:[{s:"A",t:"（___）が　いいですか。"},{s:"B",t:"あのみどりのを　ください。"}],
    ch:["どの","どんな","どれ","どちら"], ans:2,
    ex:"「どれがいいですか」= 'Mana yang bagus?'. 「どれ」untuk memilih dari banyak pilihan." },

  // ===== POLA 43: ～があります/わかります =====
  { cat:"ga_arimasu", pola:"Pola 43: ～があります/わかります", topic:"が + あります/わかります",
    solo:"わたしは　おかね（___）　あります。",
    ch:["は","を","が","に"], ans:2,
    ex:"「〜があります」= 'memiliki / ada'. Objek あります/わかります ditandai「が」bukan「を」." },
  { cat:"ga_arimasu", pola:"Pola 43: ～があります/わかります", topic:"が + あります/わかります",
    dlg:[{s:"A",t:"にほんごが（___）か。"},{s:"B",t:"すこし　わかります。"}],
    ch:["わかります","あります","います","します"], ans:0,
    ex:"「にほんごがわかります」= 'mengerti bahasa Jepang'. Objek わかります pakai「が」." },
  { cat:"ga_arimasu", pola:"Pola 43: ～があります/わかります", topic:"が + あります/わかります",
    solo:"あした　やくそく（___）　あります。",
    ch:["は","を","が","に"], ans:2,
    ex:"「やくそくがあります」= 'ada janji'. Kejadian/hal yang 'ada' menggunakan「が + あります」." },

  // ===== POLA 44: ～があります (keberadaan) =====
  { cat:"keberadaan", pola:"Pola 44: ～があります (keberadaan)", topic:"Keberadaan Benda",
    solo:"あそこに　こうえん（___）　あります。",
    ch:["は","を","が","に"], ans:2,
    ex:"「〜が　あります」= 'ada...'. Menunjukkan keberadaan benda mati. Benda = が." },
  { cat:"keberadaan", pola:"Pola 44: ～があります (keberadaan)", topic:"Keberadaan Benda",
    dlg:[{s:"A",t:"ここに　なに（___）　ありますか。"},{s:"B",t:"ポストがあります。"}],
    ch:["は","を","が","に"], ans:2,
    ex:"「なにがありますか」= 'Ada apa di sini?'. Benda yang ditanyakan pakai「が」." },
  { cat:"keberadaan", pola:"Pola 44: ～があります (keberadaan)", topic:"Keberadaan Benda",
    solo:"この　きっさてんに　ざっし（___）　まんが（___）　あります。",
    ch:["が、も","は、は","や、などが","を、を"], ans:2,
    ex:"「〜や〜などが　あります」= 'ada majalah, manga, dll'. Atau「が」untuk masing-masing." },

  // ===== POLA 45: ～が好き/嫌い/上手/下手 =====
  { cat:"suki_kirai", pola:"Pola 45: ～が好き/嫌い/上手/下手", topic:"Suka/Tidak Suka",
    solo:"わたしは　スポーツ（___）　すきです。",
    ch:["は","を","が","に"], ans:2,
    ex:"「〜がすきです」= 'suka...'. Objek好き/嫌い/上手/下手selalu pakai「が」." },
  { cat:"suki_kirai", pola:"Pola 45: ～が好き/嫌い/上手/下手", topic:"Suka/Tidak Suka",
    dlg:[{s:"A",t:"サントスさんは　りょうり（___）　じょうずですね。"},{s:"B",t:"ありがとうございます。"}],
    ch:["に","を","が","の"], ans:2,
    ex:"「りょうりが　じょうずです」= 'pandai memasak'. 上手/下手 objeknya pakai「が」." },
  { cat:"suki_kirai", pola:"Pola 45: ～が好き/嫌い/上手/下手", topic:"Suka/Tidak Suka",
    solo:"おかあさんは　やきゅう（___）　きらいです。",
    ch:["を","が","は","に"], ans:1,
    ex:"「やきゅうが　きらいです」= 'tidak suka baseball'. Objek嫌い = 「が」." },

  // ===== POLA 46: よく/だいたい/たくさん/少し/あまり/ぜんぜん =====
  { cat:"fukushi2", pola:"Pola 46: Kata Keterangan Frekuensi", topic:"Kata Keterangan",
    dlg:[{s:"A",t:"まつもとさんは　ドイツごが（___）　わかりません。"},{s:"B",t:"そうですか。"}],
    ch:["よく","たくさん","ぜんぜん","だいたい"], ans:2,
    ex:"「ぜんぜん〜ません」= 'sama sekali tidak'. Selalu dengan kalimat negatif." },
  { cat:"fukushi2", pola:"Pola 46: Kata Keterangan Frekuensi", topic:"Kata Keterangan",
    solo:"ジョンさんは　スペインごが（___）　わかります。",
    ch:["ぜんぜん","あまり","よく","すこし（negatif）"], ans:2,
    ex:"「よく　わかります」= 'sangat mengerti / mengerti dengan baik'. 「よく」dengan kalimat positif." },
  { cat:"fukushi2", pola:"Pola 46: Kata Keterangan Frekuensi", topic:"Kata Keterangan",
    dlg:[{s:"A",t:"ここは　もりが（___）　ありません。"},{s:"B",t:"そうですね、すくないですね。"}],
    ch:["よく","たくさん","ぜんぜん","あまり"], ans:3,
    ex:"「あまり〜ません」= 'tidak begitu banyak'. 「ぜんぜん」= sama sekali tidak (lebih kuat)." },

  // ===== POLA 47: ～から、～ (sebab akibat) =====
  { cat:"kara_sebab", pola:"Pola 47: ～から、～ (sebab)", topic:"Sebab-Akibat",
    solo:"いそがしいです（___）、テレビを　みません。",
    ch:["が","けど","から","でも"], ans:2,
    ex:"「〜から、〜」= 'karena..., maka...'. 「から」= karena (alasan)." },
  { cat:"kara_sebab", pola:"Pola 47: ～から、～ (sebab)", topic:"Sebab-Akibat",
    dlg:[{s:"A",t:"どうして　そとへ　でませんか。"},{s:"B",t:"あめが　ふっています（___）。"}],
    ch:["が","から","けど","でも"], ans:1,
    ex:"Jawaban alasan diakhiri「から」. 'Karena hujan turun'." },
  { cat:"kara_sebab", pola:"Pola 47: ～から、～ (sebab)", topic:"Sebab-Akibat",
    solo:"じかんが　ありません　（___）、りょこうを　しません。",
    ch:["が","でも","から","のに"], ans:2,
    ex:"「じかんがありません　から、りょこうをしません」= 'Karena tidak ada waktu, tidak bertamasya'." },

  // ===== POLA 48: どうして〜か/から =====
  { cat:"doushite", pola:"Pola 48: どうして～から", topic:"Menanyakan Alasan",
    dlg:[{s:"A",t:"（___）　はやく　かえりますか。"},{s:"B",t:"こどもの　たんじょうびですから。"}],
    ch:["なぜなら","どうして","だから","なのに"], ans:1,
    ex:"「どうして」= 'mengapa/kenapa'. Menanyakan alasan. Jawaban diakhiri「から」." },
  { cat:"doushite", pola:"Pola 48: どうして～から", topic:"Menanyakan Alasan",
    solo:"（___）あさ　しんぶんを　よみませんか。…じかんが　ありません（___）。",
    ch:["どうして、から","なに、だから","なぜ、ので","どうして、が"], ans:0,
    ex:"「どうして〜か」→ jawaban「〜から」. 'Mengapa tidak baca koran? Karena tidak ada waktu'." },
  { cat:"doushite", pola:"Pola 48: どうして～から", topic:"Menanyakan Alasan",
    dlg:[{s:"A",t:"どうして　きょうとへ　いきませんか。"},{s:"B",t:"やくそくが　あります（___）。"}],
    ch:["が","でも","から","けど"], ans:2,
    ex:"Jawaban untuk「どうして」diakhiri「から」= karena. 'Karena ada janji'." },

  // ===== POLA 49: ～があります/います (keberadaan ada/tidak) =====
  { cat:"keberadaan2", pola:"Pola 49: あります vs います", topic:"あります/います",
    solo:"にわに　ねこ（___）　います。",
    ch:["は","を","が","に"], ans:2,
    ex:"「ねこがいます」= 'ada kucing'. 「います」untuk makhluk hidup. Subyek pakai「が」." },
  { cat:"keberadaan2", pola:"Pola 49: あります vs います", topic:"あります/います",
    dlg:[{s:"A",t:"きょうしつに　せんせいが（___）。"},{s:"B",t:"はい、います。"}],
    ch:["あります","います","です","します"], ans:1,
    ex:"「せんせいがいます」= 'ada guru'. 「います」untuk orang (makhluk bergerak)." },
  { cat:"keberadaan2", pola:"Pola 49: あります vs います", topic:"あります/います",
    solo:"つくえの　うえに　ほん（___）　あります。いすの　よこに　かばん（___）　あります。",
    ch:["が、も","が、が","は、も","の、の"], ans:0,
    ex:"「ほんが　あります。かばんも　あります」= 'Ada buku. Ada tas juga'. が → も untuk 'juga'." },

  // ===== POLA 50: ～にKBがあります/います =====
  { cat:"ni_keberadaan", pola:"Pola 50: ～に～があります/います", topic:"Posisi Keberadaan",
    solo:"スーパーの　となり（___）　きっさてん（___）　あります。",
    ch:["で、が","に、が","に、を","が、に"], ans:1,
    ex:"「〔場所〕に　〔KB〕が　あります」= 'Di ... ada ...'. Tempat+に, benda+が." },
  { cat:"ni_keberadaan", pola:"Pola 50: ～に～があります/います", topic:"Posisi Keberadaan",
    dlg:[{s:"A",t:"（___）に　だれが　いますか。"},{s:"B",t:"さとうさんの　まえに　カリナさんが　います。"}],
    ch:["どこ","なに","だれ","いつ"], ans:0,
    ex:"「どこに　だれがいますか」= 'Di mana ada siapa?'. Menanyakan letak orang." },
  { cat:"ni_keberadaan", pola:"Pola 50: ～に～があります/います", topic:"Posisi Keberadaan",
    solo:"ドアの　みぎ（___）　スイッチ（___）　あります。",
    ch:["に、が","で、を","が、に","は、は"], ans:0,
    ex:"「ドアのみぎに　スイッチが　あります」= 'Di sebelah kanan pintu ada saklar'." },

  // ===== POLA 51: KBはにあります/います =====
  { cat:"wa_ni", pola:"Pola 51: ～は～にあります/います", topic:"Letak Benda/Orang",
    dlg:[{s:"A",t:"じしょは　どこに　ありますか。"},{s:"B",t:"じしょ（___）　じむしょ（___）　あります。"}],
    ch:["は、に","が、に","を、で","に、で"], ans:0,
    ex:"「〔KB〕は　〔場所〕に　あります」= 'Kamus ada di kantor'. は=topik, に=lokasi." },
  { cat:"wa_ni", pola:"Pola 51: ～は～にあります/います", topic:"Letak Benda/Orang",
    solo:"グプタさん（___）　かいぎしつ（___）　います。",
    ch:["は、に","が、で","を、に","に、が"], ans:0,
    ex:"「グプタさんは　かいぎしつに　います」= 'Gupta ada di ruang rapat'." },
  { cat:"wa_ni", pola:"Pola 51: ～は～にあります/います", topic:"Letak Benda/Orang",
    dlg:[{s:"A",t:"きむらさんは（___）に　いますか。"},{s:"B",t:"あそこに　います。"}],
    ch:["どれ","どの","どこ","どちら"], ans:2,
    ex:"「どこに　いますか」= 'Ada di mana?'. Menanyakan lokasi orang." },

  // ===== POLA 52: KBのposisiにKBがあります =====
  { cat:"ichi_posisi", pola:"Pola 52: ～の posisi に ～があります", topic:"Posisi Relatif",
    solo:"ゆうびんきょくの　となり（___）　ぎんこう（___）　あります。",
    ch:["に、が","で、を","が、に","は、を"], ans:0,
    ex:"「〜のとなりに　〜があります」= 'Di sebelah ... ada ...'. Posisi + に, benda + が." },
  { cat:"ichi_posisi", pola:"Pola 52: ～の posisi に ～があります", topic:"Posisi Relatif",
    dlg:[{s:"A",t:"テーブルと　たなの（___）に　いすが　あります。"},{s:"B",t:"わかりました。"}],
    ch:["うえ","した","あいだ","うしろ"], ans:2,
    ex:"「〜と〜のあいだに」= 'di antara ... dan ...'. 「あいだ」untuk dua benda referensi." },
  { cat:"ichi_posisi", pola:"Pola 52: ～の posisi に ～があります", topic:"Posisi Relatif",
    solo:"まつもとさんの（___）に　いしかわさんが　います。",
    ch:["まえ","あいだ","そと","どこ"], ans:0,
    ex:"「〜のまえに　います」= 'ada di depan ~'. Kata posisi: まえ, うしろ, みぎ, ひだり, dll." },

  // ===== POLA 53: ～や～など =====
  { cat:"ya_nado", pola:"Pola 53: ～や～など", topic:"Partikel や",
    solo:"はこの　なかに　てがみ（___）　しゃしん（___）　あります。",
    ch:["と、が","や、などが","も、もが","か、かが"], ans:1,
    ex:"「〜や〜などが　あります」= 'ada ... dan ... (dan lainnya)'. 「や」= dan (tidak lengkap)." },
  { cat:"ya_nado", pola:"Pola 53: ～や～など", topic:"Partikel や",
    dlg:[{s:"A",t:"かばんに　なにが　ありますか。"},{s:"B",t:"さいふ（___）　けいたい（___）　あります。"}],
    ch:["と、が","は、は","や、などが","の、の"], ans:2,
    ex:"「さいふや　けいたいなどが　あります」= 'Ada dompet, HP, dsb'. 「や〜など」tidak menyebut semua." },
  { cat:"ya_nado", pola:"Pola 53: ～や～など", topic:"Partikel や",
    solo:"かいぎしつに　ミラーさん（___）　やまださん（___）　います。",
    ch:["と、が","や、などが","も、もが","か、かが"], ans:1,
    ex:"「〜や〜などが　います」= 'Ada Miller, Yamada, dsb'. 「など」menunjukkan masih ada yang lain." }

  // ===== POLA 54: (KB)が (Ket. jumlah)あります =====
  ,{ cat:"bab11", pola:"Pola 54: ～が～あります (jumlah benda)", topic:"Bab 11 - Jumlah Benda",
    solo:"りんご（___）　とお　あります。",
    ch:["を","に","が","で"], ans:2,
    ex:"Jumlah benda pada pola ini memakai 「が」 + あります. Jadi: りんごが とお あります." }
  ,{ cat:"bab11", pola:"Pola 54: ～が～あります (jumlah benda)", topic:"Bab 11 - Jumlah Benda",
    dlg:[{s:"A",t:"この　はこに　みかんが　むっつ　あります。"},{s:"B",t:"みかんが　（___）　ありますか。"}],
    ch:["なんにん","いくつ","なんかい","どのくらい"], ans:1,
    ex:"Untuk menanyakan jumlah benda kecil, pakai 「いくつ」." }
  ,{ cat:"bab11", pola:"Pola 54: ～が～あります (jumlah benda)", topic:"Bab 11 - Jumlah Benda",
    solo:"スイカが　ひとつ（___）。",
    ch:["います","かかります","あります","ですか"], ans:2,
    ex:"Benda mati memakai あります. Jadi: スイカが ひとつ あります." }

  // ===== POLA 55: (Ket)の(KB)を(ket.jumlah)かいました =====
  ,{ cat:"bab11", pola:"Pola 55: ～を～かいました", topic:"Bab 11 - Membeli Jumlah",
    solo:"きって（___）　ごまい　かいました。",
    ch:["が","を","に","で"], ans:1,
    ex:"Karena diikuti kata kerja membeli (かいました), objek memakai 「を」." }
  ,{ cat:"bab11", pola:"Pola 55: ～を～かいました", topic:"Bab 11 - Membeli Jumlah",
    dlg:[{s:"A",t:"なにを　かいましたか。"},{s:"B",t:"はがきを　さん（___）　かいました。"}],
    ch:["だい","にん","まい","かい"], ans:2,
    ex:"はがき dihitung dengan satuan lembar, jadi pakai 「まい」." }
  ,{ cat:"bab11", pola:"Pola 55: ～を～かいました", topic:"Bab 11 - Membeli Jumlah",
    solo:"くるまを　いち（___）　かいました。",
    ch:["だい","まい","にん","つ"], ans:0,
    ex:"Untuk mesin/mobil pakai satuan 「だい」." }

  // ===== POLA 56: (KB)が (Jumlah orang)人 います =====
  ,{ cat:"bab11", pola:"Pola 56: ～が～人います", topic:"Bab 11 - Jumlah Orang",
    solo:"この　クラスに　りゅうがくせいが　よにん（___）。",
    ch:["あります","います","です","かかります"], ans:1,
    ex:"Orang/makhluk hidup pakai 「います」." }
  ,{ cat:"bab11", pola:"Pola 56: ～が～人います", topic:"Bab 11 - Jumlah Orang",
    dlg:[{s:"A",t:"かぞくは　なんにん　いますか。"},{s:"B",t:"ろくにん（___）。"}],
    ch:["あります","います","ですか","でした"], ans:1,
    ex:"Menjawab jumlah anggota keluarga: ～にん います." }
  ,{ cat:"bab11", pola:"Pola 56: ～が～人います", topic:"Bab 11 - Jumlah Orang",
    solo:"かいしゃの　しゃいんが　100にん（___）　います。",
    ch:["ぐらい","だけ","まで","しか"], ans:0,
    ex:"「ぐらい」artinya kira-kira/kurang lebih." }

  // ===== POLA 57: (Ket waktu)に (berapa kali)かい ... =====
  ,{ cat:"bab11", pola:"Pola 57: ～に～かい", topic:"Bab 11 - Frekuensi",
    solo:"1しゅうかんに　1（___）　えいがを　みます。",
    ch:["にん","だい","かい","まい"], ans:2,
    ex:"Frekuensi 'kali' memakai satuan 「かい」." }
  ,{ cat:"bab11", pola:"Pola 57: ～に～かい", topic:"Bab 11 - Frekuensi",
    dlg:[{s:"A",t:"1かげつに　なんかい　ほんを　かりますか。"},{s:"B",t:"8かい（___）　かります。"}],
    ch:["だけ","ぐらい","まで","しか"], ans:1,
    ex:"Untuk bilang kira-kira, tambahkan 「ぐらい」 setelah angka frekuensi." }
  ,{ cat:"bab11", pola:"Pola 57: ～に～かい", topic:"Bab 11 - Frekuensi",
    solo:"いちねんに　ごかい　ワインを　（___）。",
    ch:["のみます","のみません","のみました","のめます"], ans:0,
    ex:"Kalimat kebiasaan/frekuensi umum biasanya memakai bentuk non-lampau 「ます」." }

  // ===== POLA 58: (Ket durasi) (KB)を (KK) =====
  ,{ cat:"bab11", pola:"Pola 58: durasi + を + KK", topic:"Bab 11 - Durasi Aktivitas",
    solo:"くにで　ごしゅうかん　にほんごを　（___）。",
    ch:["べんきょうします","べんきょうしました","べんきょうしません","べんきょうできません"], ans:1,
    ex:"Contoh aktivitas yang sudah dilakukan selama durasi tertentu memakai bentuk lampau: べんきょうしました." }
  ,{ cat:"bab11", pola:"Pola 58: durasi + を + KK", topic:"Bab 11 - Durasi Aktivitas",
    dlg:[{s:"A",t:"こうこうで　さんねんかん　なにを　しましたか。"},{s:"B",t:"クラブに　（___）。"}],
    ch:["さんかしました","さんかします","さんかしません","さんかでした"], ans:0,
    ex:"Kalimat pengalaman lampau: さんかしました." }
  ,{ cat:"bab11", pola:"Pola 58: durasi + を + KK", topic:"Bab 11 - Durasi Aktivitas",
    solo:"7にちかん　りょこうを　（___）。",
    ch:["します","しませんか","しましょう","しましたか"], ans:0,
    ex:"Pola dasar rutinitas/pernyataan umum bisa memakai 「します」." }

  // ===== POLA 60-62: BAB 12 - Sifat Benda & Sifat い =====
  ,{ cat:"bab12_sifat", pola:"Pola 60: ～は [K.Sifat(な)] ～です/でした", topic:"Bab 12 - Sifat Benda",
    dlg:[{s:"A",t:"サントスさんは　げんきですか。"},{s:"B",t:"はい、（___）。"}],
    ch:["げんきです","げんきじゃありません","げんきでした","げんくないです"], ans:0,
    ex:"Sifat [な] positif sekarang: 「元気です」= sehat/bugar. Jawaban persis mengulangi pola." }
  ,{ cat:"bab12_sifat", pola:"Pola 60: ～は [K.Sifat(な)] ～です/でした", topic:"Bab 12 - Sifat Benda",
    solo:"きのうの　あめは　すてき（___）。",
    ch:["です","じゃありません","でした","だった"], ans:2,
    ex:"Lampau: [な]sifat + でした. 「すてきでした」= indah/bagus (kemarin)." }
  ,{ cat:"bab12_sifat", pola:"Pola 60: ～は [K.Sifat(な)] ～です/でした", topic:"Bab 12 - Sifat Benda",
    dlg:[{s:"A",t:"ホテルは　きれいでしたか。"},{s:"B",t:"いいえ、きれい（___）。"}],
    ch:["じゃありませんでした","じゃありません","ではありました","ではないです"], ans:0,
    ex:"Lampau negatif: 「きれいじゃありませんでした」= tidak indah (dulu)." }

  // ===== POLA 63-65: BAB 12 - Sifat い =====
  ,{ cat:"bab12_sifat_i", pola:"Pola 63: ～は [K.Sifat(い)] ～いです/かったです", topic:"Bab 12 - Sifat い",
    solo:"このえいがは　とても　おもしろい（___）。",
    ch:["です","でした","ですか","ました"], ans:0,
    ex:"Sifat い positif sekarang: 「おもしろいです」= menarik. Ujung い tetap, langsung tambah です." }
  ,{ cat:"bab12_sifat_i", pola:"Pola 63: ～は [K.Sifat(い)] ～いです/かったです", topic:"Bab 12 - Sifat い",
    dlg:[{s:"A",t:"パーティーの　りょうりは　おいしかったですか。"},{s:"B",t:"はい、（___）。"}],
    ch:["おいしかったです","おいしいです","おいしくないです","おいしくなかったです"], ans:0,
    ex:"Lampau: い → かった + です. 「おいしかったです」= enak (dulu)." }
  ,{ cat:"bab12_sifat_i", pola:"Pola 63: ～は [K.Sifat(い)] ～いです/かったです", topic:"Bab 12 - Sifat い",
    solo:"セーターは　どうでしたか。パン は　あまり　（___）。",
    ch:["あまくないです","あまいです","あまかったです","あまくなかったです"], ans:0,
    ex:"Negatif sekarang: い → くない + です. 「あまくないです」= tidak begitu manis." }

  // ===== POLA 66-68: BAB 12 - Perbandingan dengan より =====
  ,{ cat:"bab12_perbandingan", pola:"Pola 66: [KB1]は [KB2]より [K.Sifat]です", topic:"Bab 12 - Perbandingan",
    solo:"とうきょうは　おおさかより　（___）です。",
    ch:["ことに","とくに","おおきい","より大きい"], ans:2,
    ex:"Pola perbandingan: KB1 は KB2 より Sifat です. 「大きい」= besar." }
  ,{ cat:"bab12_perbandingan", pola:"Pola 66: [KB1]は [KB2]より [K.Sifat]です", topic:"Bab 12 - Perbandingan",
    dlg:[{s:"A",t:"ボゴールは　ソロより　（___）ですか。"},{s:"B",t:"ええ、ボゴールの　ほうが　すずしいです。"}],
    ch:["どう","どんな","すずしい","ゆうめい"], ans:2,
    ex:"Jawab dengan sifat yang cocok. 「すずしい」= sejuk." }
  ,{ cat:"bab12_perbandingan", pola:"Pola 66: [KB1]は [KB2]より [K.Sifat]です", topic:"Bab 12 - Perbandingan",
    solo:"このシャツは　そのシャツより　（___）です。",
    ch:["ちいさい","あたらしい","やすい","たかい"], ans:2,
    ex:"Pola dasar: yang pertama dibanding dengan yang kedua. 「やすい」= murah." }

  // ===== POLA 69-71: BAB 12 - Pertanyaan Pilihan dengan どちら =====
  ,{ cat:"bab12_dochira", pola:"Pola 69: [KB1]と [KB2]と どちらが [K.Sifat]ですか", topic:"Bab 12 - どちら",
    dlg:[{s:"A",t:"ほんと　えいがと　どちらが（___）ですか。"},{s:"B",t:"えいがの　ほうが　おもしろいです。"}],
    ch:["おもしろい","おもしろいいいです","より好き","と同じ"], ans:0,
    ex:"Pertanyaan perbandingan dua hal: KB1 と KB2 と どちらが Sifat ですか." }
  ,{ cat:"bab12_dochira", pola:"Pola 69: [KB1]と [KB2]と どちらが [K.Sifat]ですか", topic:"Bab 12 - どちら",
    solo:"サッカーと　やきゅうと　どちらが　むずかしいですか。…サッカーの　ほうが　（___）。",
    ch:["むずかしいです","むずかしい","より難しい","ほうが難しい"], ans:0,
    ex:"Jawab dengan 「~ の ほうが ~です」 untuk memilih salah satu. 「むずかしい」= susah." }
  ,{ cat:"bab12_dochira", pola:"Pola 69: [KB1]と [KB2]と どちらが [K.Sifat]ですか", topic:"Bab 12 - どちら",
    dlg:[{s:"A",t:"にほんと　アメリカと　どちらが　にぎやかですか。"},{s:"B",t:"（___）　にぎやかです。"}],
    ch:["どちらも","どちらか","どちらまで","どちらと"], ans:0,
    ex:"Jawab 「どちらも」 jika dua pilihan sama-sama memenuhi sifatnya." }

  // ===== POLA 72-74: BAB 12 - Superlatif dengan いちばん =====
  ,{ cat:"bab12_ichiban", pola:"Pola 72: [KB]の 中で なにが いちばん [K.Sifat]ですか", topic:"Bab 12 - いちばん",
    solo:"おかあさんの　りょうりの　なかで　なにが　（___）　おいしいですか。",
    ch:["いちばん","ほぼ","やや","ずっと"], ans:0,
    ex:"Superlatif: 「いちばん」= paling. Pola: [KB] の 中で [Kata Tanya] が いちばん [Sifat]." }
  ,{ cat:"bab12_ichiban", pola:"Pola 72: [KB]の 中で なにが いちばん [K.Sifat]ですか", topic:"Bab 12 - いちばん",
    dlg:[{s:"A",t:"すべての　ほんの　なかで　どれが　いちばん　（___）ですか。"},{s:"B",t:"このほんです。"}],
    ch:["おもしろい","とても","より","ほうが"], ans:0,
    ex:"Jawab dengan benda yang dipilih. 「どれ」untuk memilih benda." }
  ,{ cat:"bab12_ichiban", pola:"Pola 72: [KB]の 中で なにが いちばん [K.Sifat]ですか", topic:"Bab 12 - いちばん",
    solo:"せかいの　なかで　どこが　いちばん　きれいですか。…（___）が　いちばん　きれいです。",
    ch:["おきなわ","ここ","そこ","どこ"], ans:0,
    ex:"Jawab dengan tempat/pilihan spesifik. 「Jawaban の が いちばん ...」." }
];

const BUNPO_QUIZ_CATEGORIES = [
  { id:"all",       name:"Semua",        icon:"⭐" },
  { id:"copula",    name:"は～です",      icon:"💬" },
  { id:"kosoado",   name:"Ko-So-A-Do",   icon:"👉" },
  { id:"no",        name:"Partikel の",   icon:"🔗" },
  { id:"movement",  name:"Gerakan",       icon:"🚶" },
  { id:"keiyoshi",  name:"Kata Sifat",    icon:"🎨" },
  { id:"keberadaan",name:"あります",      icon:"📍" },
  { id:"keberadaan2",name:"います",       icon:"🧍" },
  { id:"ni_keberadaan",name:"Posisi",     icon:"🗺️" },
  { id:"ageru_morau",name:"あげる/もらう",icon:"🎁" },
  { id:"kara_sebab",name:"から (sebab)",  icon:"💡" },
  { id:"suki_kirai",name:"好き/嫌い",     icon:"❤️" },
  { id:"fukushi2",  name:"Kata Ket.",     icon:"📊" },
  { id:"masu",      name:"ます活用",      icon:"📝" },
  { id:"bab11",     name:"Bab 11",        icon:"1️⃣1️⃣" },
  { id:"bab12_sifat", name:"Bab 12 - Sifat [な]", icon:"✨" },
  { id:"bab12_sifat_i", name:"Bab 12 - Sifat [い]", icon:"🌡️" },
  { id:"bab12_perbandingan", name:"Bab 12 - Perbandingan", icon:"⚖️" },
  { id:"bab12_dochira", name:"Bab 12 - どちら", icon:"🤔" },
  { id:"bab12_ichiban", name:"Bab 12 - いちばん", icon:"🏆" },
];

window.BUNPO_QUIZ_QUESTIONS = BUNPO_QUIZ_QUESTIONS;
window.BUNPO_QUIZ_CATEGORIES = BUNPO_QUIZ_CATEGORIES;
