const vocab = [
  {jp:"わたし",rom:"watashi",id:"Saya / Aku",cat:"Bab 1"},
  {jp:"あなた",rom:"anata",id:"Kamu / Anda",cat:"Bab 1"},
  {jp:"あのひと / あのかた",rom:"ano hito / ano kata",id:"Orang itu / Beliau (sopan)",cat:"Bab 1"},
  {jp:"〜さん",rom:"~san",id:"Sebutan hormat (Pak/Bu/Sdr)",cat:"Bab 1"},
  {jp:"〜ちゃん",rom:"~chan",id:"Sebutan akrab / sayang",cat:"Bab 1"},
  {jp:"せんせい",rom:"sensei",id:"Guru / Sensei",cat:"Bab 1"},
  {jp:"〜さい",rom:"~sai",id:"... tahun (umur)",cat:"Bab 1"},
  {jp:"なんさい",rom:"nansai",id:"Berapa tahun (umur)?",cat:"Bab 1"},
  {jp:"おいくつ",rom:"oikutsu",id:"Berapa umur Anda? (sopan)",cat:"Bab 1"},
  {jp:"はい",rom:"hai",id:"Ya / Iya",cat:"Bab 1"},
  {jp:"いいえ",rom:"iie",id:"Tidak / Bukan",cat:"Bab 1"},
  {jp:"はじめまして",rom:"hajimemashite",id:"Senang berkenalan dengan Anda",cat:"Bab 1"},
  {jp:"〜からきました",rom:"~kara kimashita",id:"Saya berasal dari ~",cat:"Bab 1"},
  {jp:"どうぞよろしく",rom:"douzo yoroshiku",id:"Senang berkenalan (mohon bantuannya)",cat:"Bab 1"},
  {jp:"おなまえは？",rom:"onamae wa?",id:"Siapa nama Anda?",cat:"Bab 1"},
  {jp:"きょうし",rom:"kyoushi",id:"Guru / Pengajar",cat:"Bab 1"},
  {jp:"がくせい",rom:"gakusei",id:"Murid / Mahasiswa",cat:"Bab 1"},
  {jp:"ぎんこういん",rom:"ginkouin",id:"Pegawai bank",cat:"Bab 1"},
  {jp:"かいしゃいん",rom:"kaishain",id:"Karyawan perusahaan",cat:"Bab 1"},
  {jp:"いしゃ",rom:"isha",id:"Dokter",cat:"Bab 1"},
  {jp:"けんきゅうしゃ",rom:"kenkyuusha",id:"Peneliti",cat:"Bab 1"},
  {jp:"だいがく",rom:"daigaku",id:"Universitas",cat:"Bab 1"},
  {jp:"これ",rom:"kore",id:"Ini (dekat pembicara)",cat:"Bab 2"},
  {jp:"それ",rom:"sore",id:"Itu (dekat lawan bicara)",cat:"Bab 2"},
  {jp:"あれ",rom:"are",id:"Itu (jauh dari keduanya)",cat:"Bab 2"},
  {jp:"ほん",rom:"hon",id:"Buku",cat:"Bab 2"},
  {jp:"じしょ",rom:"jisho",id:"Kamus",cat:"Bab 2"},
  {jp:"ざっし",rom:"zasshi",id:"Majalah",cat:"Bab 2"},
  {jp:"しんぶん",rom:"shinbun",id:"Koran",cat:"Bab 2"},
  {jp:"ノート",rom:"nooto",id:"Buku catatan",cat:"Bab 2"},
  {jp:"てちょう",rom:"techou",id:"Buku saku / Agenda",cat:"Bab 2"},
  {jp:"めいし",rom:"meishi",id:"Kartu nama",cat:"Bab 2"},
  {jp:"えんぴつ",rom:"enpitsu",id:"Pensil",cat:"Bab 2"},
  {jp:"ボールペン",rom:"boorupen",id:"Bolpoin",cat:"Bab 2"},
  {jp:"かぎ",rom:"kagi",id:"Kunci",cat:"Bab 2"},
  {jp:"とけい",rom:"tokei",id:"Jam / Arloji",cat:"Bab 2"},
  {jp:"かさ",rom:"kasa",id:"Payung",cat:"Bab 2"},
  {jp:"かばん",rom:"kaban",id:"Tas",cat:"Bab 2"},
  {jp:"テレビ",rom:"terebi",id:"Televisi",cat:"Bab 2"},
  {jp:"ラジオ",rom:"rajio",id:"Radio",cat:"Bab 2"},
  {jp:"カメラ",rom:"kamera",id:"Kamera",cat:"Bab 2"},
  {jp:"コンピューター",rom:"konpyuutaa",id:"Komputer",cat:"Bab 2"},
  {jp:"くるま",rom:"kuruma",id:"Mobil",cat:"Bab 2"},
  {jp:"つくえ",rom:"tsukue",id:"Meja",cat:"Bab 2"},
  {jp:"いす",rom:"isu",id:"Kursi",cat:"Bab 2"},
  {jp:"おみやげ",rom:"omiyage",id:"Oleh-oleh / Suvenir",cat:"Bab 2"},
  {jp:"チョコレート",rom:"chokoreto",id:"Coklat",cat:"Bab 2"},
  {jp:"コーヒー",rom:"koohii",id:"Kopi",cat:"Bab 2"},
  {jp:"えいご（英語）",rom:"eigo",id:"Bahasa Inggris",cat:"Bab 2"},
  {jp:"にほんご（日本語）",rom:"nihongo",id:"Bahasa Jepang",cat:"Bab 2"},
  {jp:"あのう",rom:"anou",id:"Eee… (ungkapan ragu-ragu)",cat:"Bab 2"},
  {jp:"えっ",rom:"e",id:"Eh (ungkapan kejutan)",cat:"Bab 2"},
  {jp:"どうぞ",rom:"douzo",id:"Silakan (saat menawarkan sesuatu)",cat:"Bab 2"},
  {jp:"どうも ありがとう ございます",rom:"doumo arigatou gozaimasu",id:"Terima kasih (banyak/formal)",cat:"Bab 2"},
  {jp:"そうですか",rom:"sou desu ka",id:"Oh, begitu ya / Oh, ya",cat:"Bab 2"},
  {jp:"ちがいます",rom:"chigaimasu",id:"Bukan / Tidak / Salah",cat:"Bab 2"},
  {jp:"これから お世話に なります",rom:"kore kara osewa ni narimasu",id:"Mulai sekarang mohon bantuannya",cat:"Bab 2"},
  {jp:"こちらこそ どうぞ よろしく お願いします",rom:"kochira koso douzo yoroshiku onegai shimasu",id:"Ya, sama-sama (jawaban dari よろしく)",cat:"Bab 2"},
  {jp:"ここ",rom:"koko",id:"Di sini",cat:"Bab 3"},
  {jp:"そこ",rom:"soko",id:"Di situ",cat:"Bab 3"},
  {jp:"あそこ",rom:"asoko",id:"Di sana",cat:"Bab 3"},
  {jp:"どこ",rom:"doko",id:"Di mana?",cat:"Bab 3"},
  {jp:"こちら",rom:"kochira",id:"Ke sini / Ini (arah, sopan)",cat:"Bab 3"},
  {jp:"そちら",rom:"sochira",id:"Ke situ (arah, sopan)",cat:"Bab 3"},
  {jp:"あちら",rom:"achira",id:"Ke sana (arah, sopan)",cat:"Bab 3"},
  {jp:"どちら",rom:"dochira",id:"Yang mana? / Ke mana?",cat:"Bab 3"},
  {jp:"きょうしつ",rom:"kyoushitsu",id:"Ruang kelas",cat:"Bab 3"},
  {jp:"しょくどう",rom:"shokudou",id:"Kafetaria / Kantin",cat:"Bab 3"},
  {jp:"じむしょ",rom:"jimusho",id:"Kantor",cat:"Bab 3"},
  {jp:"かいぎしつ",rom:"kaigishitsu",id:"Ruang rapat",cat:"Bab 3"},
  {jp:"うけつけ",rom:"uketsuke",id:"Resepsionis / Meja penerima tamu",cat:"Bab 3"},
  {jp:"ロビー",rom:"robii",id:"Lobi",cat:"Bab 3"},
  {jp:"へや",rom:"heya",id:"Kamar / Ruangan",cat:"Bab 3"},
  {jp:"トイレ／おてあらい",rom:"toire / otearai",id:"Toilet / Kamar mandi",cat:"Bab 3"},
  {jp:"かいだん",rom:"kaidan",id:"Tangga",cat:"Bab 3"},
  {jp:"エレベーター",rom:"erebeetaa",id:"Lift / Elevator",cat:"Bab 3"},
  {jp:"エスカレーター",rom:"esukareetaa",id:"Eskalator",cat:"Bab 3"},
  {jp:"ちか",rom:"chika",id:"Lantai bawah tanah / Basement",cat:"Bab 3"},
  {jp:"〜かい",rom:"~kai / ~gai",id:"Lantai ke~ (gedung)",cat:"Bab 3"},
  {jp:"なんがい",rom:"nangai",id:"Lantai berapa?",cat:"Bab 3"},
  {jp:"うりば",rom:"uriba",id:"Bagian / Departemen toko",cat:"Bab 3"},
  {jp:"いくら",rom:"ikura",id:"Berapa harganya?",cat:"Bab 3"},
  {jp:"〜えん",rom:"~en",id:"~ yen (mata uang Jepang)",cat:"Bab 3"},
  {jp:"うち",rom:"uchi",id:"Rumah",cat:"Bab 3"},
  {jp:"でんわ（電話）",rom:"denwa",id:"Telepon",cat:"Bab 3"},
  {jp:"くつ（靴）",rom:"kutsu",id:"Sepatu",cat:"Bab 3"},
  {jp:"ネクタイ",rom:"nekutai",id:"Dasi",cat:"Bab 3"},
  {jp:"ワイン",rom:"wain",id:"Wine / Anggur",cat:"Bab 3"},
  {jp:"たばこ（煙草）",rom:"tabako",id:"Rokok",cat:"Bab 3"},
  {jp:"うりば（売り場）",rom:"uriba",id:"Bagian / Departemen toko",cat:"Bab 3"},
  {jp:"まん（万）",rom:"man",id:"Sepuluh ribu",cat:"Bab 3"},
  {jp:"すみません",rom:"sumimasen",id:"Permisi / Maaf",cat:"Bab 3"},
  {jp:"〜でございます",rom:"~de gozaimasu",id:"Adalah (sopan/formal)",cat:"Bab 3"},
  {jp:"［～を］みせてください（見せてください）",rom:"misete kudasai",id:"Mohon tunjukkan",cat:"Bab 3"},
  {jp:"じゃ",rom:"ja",id:"Baiklah / Jadi (informal)",cat:"Bab 3"},
  {jp:"いま",rom:"ima",id:"Sekarang",cat:"Bab 4"},
  {jp:"〜じ",rom:"~ji",id:"Jam ~ (pukul)",cat:"Bab 4"},
  {jp:"〜ふん／ぷん",rom:"~fun / ~pun",id:"~ menit",cat:"Bab 4"},
  {jp:"はん",rom:"han",id:"Setengah (30 menit)",cat:"Bab 4"},
  {jp:"なんじ",rom:"nanji",id:"Jam berapa?",cat:"Bab 4"},
  {jp:"なんぷん",rom:"nanpun",id:"Berapa menit?",cat:"Bab 4"},
  {jp:"ごぜん",rom:"gozen",id:"Pagi / AM",cat:"Bab 4"},
  {jp:"ごご",rom:"gogo",id:"Sore / PM",cat:"Bab 4"},
  {jp:"あさ",rom:"asa",id:"Pagi",cat:"Bab 4"},
  {jp:"ひる",rom:"hiru",id:"Siang",cat:"Bab 4"},
  {jp:"ばん／よる",rom:"ban / yoru",id:"Malam",cat:"Bab 4"},
  {jp:"おととい",rom:"ototoi",id:"Kemarin lusa",cat:"Bab 4"},
  {jp:"きのう",rom:"kinou",id:"Kemarin",cat:"Bab 4"},
  {jp:"きょう",rom:"kyou",id:"Hari ini",cat:"Bab 4"},
  {jp:"あした",rom:"ashita",id:"Besok",cat:"Bab 4"},
  {jp:"あさって",rom:"asatte",id:"Lusa",cat:"Bab 4"},
  {jp:"けさ",rom:"kesa",id:"Pagi ini",cat:"Bab 4"},
  {jp:"こんばん",rom:"konban",id:"Malam ini",cat:"Bab 4"},
  {jp:"まいにち",rom:"mainichi",id:"Setiap hari",cat:"Bab 4"},
  {jp:"まいあさ",rom:"maiasa",id:"Setiap pagi",cat:"Bab 4"},
  {jp:"げつようび",rom:"getsuyoubi",id:"Hari Senin",cat:"Bab 4"},
  {jp:"かようび",rom:"kayoubi",id:"Hari Selasa",cat:"Bab 4"},
  {jp:"すいようび",rom:"suiyoubi",id:"Hari Rabu",cat:"Bab 4"},
  {jp:"もくようび",rom:"mokuyoubi",id:"Hari Kamis",cat:"Bab 4"},
  {jp:"きんようび",rom:"kinyoubi",id:"Hari Jumat",cat:"Bab 4"},
  {jp:"どようび",rom:"doyoubi",id:"Hari Sabtu",cat:"Bab 4"},
  {jp:"にちようび",rom:"nichiyoubi",id:"Hari Minggu",cat:"Bab 4"},
  {jp:"やすみ",rom:"yasumi",id:"Hari libur / Istirahat",cat:"Bab 4"},
  {jp:"しけん",rom:"shiken",id:"Ujian / Tes",cat:"Bab 4"},
  {jp:"かいぎ",rom:"kaigi",id:"Rapat",cat:"Bab 4"},
  {jp:"えいが",rom:"eiga",id:"Film / Bioskop",cat:"Bab 4"},
  {jp:"おきます",rom:"okimasu",id:"Bangun (tidur)",cat:"Bab 4"},
  {jp:"ねます",rom:"nemasu",id:"Tidur",cat:"Bab 4"},
  {jp:"はたらきます",rom:"hatarakimasu",id:"Bekerja",cat:"Bab 4"},
  {jp:"やすみます",rom:"yasumimasu",id:"Beristirahat / Libur",cat:"Bab 4"},
  {jp:"べんきょうします",rom:"benkyou shimasu",id:"Belajar",cat:"Bab 4"},
  {jp:"おわります",rom:"owarimasu",id:"Selesai / Berakhir",cat:"Bab 4"},
  {jp:"いきます",rom:"ikimasu",id:"Pergi",cat:"Bab 5"},
  {jp:"きます",rom:"kimasu",id:"Datang",cat:"Bab 5"},
  {jp:"かえります",rom:"kaerimasu",id:"Pulang",cat:"Bab 5"},
  {jp:"がっこう",rom:"gakkou",id:"Sekolah",cat:"Bab 5"},
  {jp:"スーパー",rom:"suupaa",id:"Supermarket",cat:"Bab 5"},
  {jp:"えき",rom:"eki",id:"Stasiun (kereta)",cat:"Bab 5"},
  {jp:"ひこうき",rom:"hikouki",id:"Pesawat terbang",cat:"Bab 5"},
  {jp:"ふね",rom:"fune",id:"Kapal",cat:"Bab 5"},
  {jp:"でんしゃ",rom:"densha",id:"Kereta listrik",cat:"Bab 5"},
  {jp:"ちかてつ",rom:"chikatetsu",id:"Kereta bawah tanah / MRT",cat:"Bab 5"},
  {jp:"しんかんせん",rom:"shinkansen",id:"Kereta cepat (Shinkansen)",cat:"Bab 5"},
  {jp:"バス",rom:"basu",id:"Bus",cat:"Bab 5"},
  {jp:"タクシー",rom:"takushii",id:"Taksi",cat:"Bab 5"},
  {jp:"じてんしゃ",rom:"jitensha",id:"Sepeda",cat:"Bab 5"},
  {jp:"あるいて",rom:"aruite",id:"Dengan berjalan kaki",cat:"Bab 5"},
  {jp:"ともだち",rom:"tomodachi",id:"Teman",cat:"Bab 5"},
  {jp:"かれ",rom:"kare",id:"Dia (laki-laki) / Pacar",cat:"Bab 5"},
  {jp:"きょねん",rom:"kyonen",id:"Tahun lalu",cat:"Bab 5"},
  {jp:"ことし",rom:"kotoshi",id:"Tahun ini",cat:"Bab 5"},
  {jp:"らいねん",rom:"rainen",id:"Tahun depan",cat:"Bab 5"},
  {jp:"なんねん",rom:"nannen",id:"Tahun berapa?",cat:"Bab 5"},
  {jp:"たんじょうび",rom:"tanjoubi",id:"Hari ulang tahun",cat:"Bab 5"},
  {jp:"ふつう",rom:"futsuu",id:"Kereta lokal (lambat)",cat:"Bab 5"},
  {jp:"きゅうこう",rom:"kyuukou",id:"Kereta ekspres",cat:"Bab 5"},
  {jp:"とっきゅう",rom:"tokkyuu",id:"Kereta super ekspres",cat:"Bab 5"},
  {jp:"デパート",rom:"depaato",id:"Pusat perbelanjaan / Department store",cat:"Bab 5"},
  {jp:"ぎんこう",rom:"ginkou",id:"Bank",cat:"Bab 5"},
  {jp:"ゆうびんきょく",rom:"yuubinkyoku",id:"Kantor pos",cat:"Bab 5"},
  {jp:"としょかん",rom:"toshokan",id:"Perpustakaan",cat:"Bab 5"},
  {jp:"びじゅつかん",rom:"bijutsukan",id:"Museum seni",cat:"Bab 5"},
  {jp:"ひと（人）",rom:"hito",id:"Orang",cat:"Bab 5"},
  {jp:"かのじょ（彼女）",rom:"kanojo",id:"Dia (perempuan) / Pacar perempuan",cat:"Bab 5"},
  {jp:"かぞく（家族）",rom:"kazoku",id:"Keluarga",cat:"Bab 5"},
  {jp:"ひとりで（一人で）",rom:"hitori de",id:"Sendirian",cat:"Bab 5"},
  {jp:"せんしゅう（先週）",rom:"senshuu",id:"Minggu lalu",cat:"Bab 5"},
  {jp:"こんしゅう（今週）",rom:"konshuu",id:"Minggu ini",cat:"Bab 5"},
  {jp:"らいしゅう（来週）",rom:"raishuu",id:"Minggu depan",cat:"Bab 5"},
  {jp:"せんげつ（先月）",rom:"sengetsu",id:"Bulan lalu",cat:"Bab 5"},
  {jp:"こんげつ（今月）",rom:"kongetsu",id:"Bulan ini",cat:"Bab 5"},
  {jp:"らいげつ（来月）",rom:"raigetsu",id:"Bulan depan",cat:"Bab 5"},
  {jp:"〜ねん（〜年）",rom:"~nen",id:"Tahun ~",cat:"Bab 5"},
  {jp:"〜がつ（〜月）",rom:"~gatsu",id:"Bulan ~",cat:"Bab 5"},
  {jp:"なんがつ（何月）",rom:"nangatsu",id:"Bulan apa?",cat:"Bab 5"},
  {jp:"ついたち（1日）",rom:"tsuitachi",id:"Tanggal satu",cat:"Bab 5"},
  {jp:"ふつか（2日）",rom:"futsuka",id:"Tanggal dua / dua hari",cat:"Bab 5"},
  {jp:"みっか（3日）",rom:"mikka",id:"Tanggal tiga / tiga hari",cat:"Bab 5"},
  {jp:"よっか（4日）",rom:"yokka",id:"Tanggal empat / empat hari",cat:"Bab 5"},
  {jp:"いつか（5日）",rom:"itsuka",id:"Tanggal lima / lima hari",cat:"Bab 5"},
  {jp:"むいか（6日）",rom:"muika",id:"Tanggal enam / enam hari",cat:"Bab 5"},
  {jp:"なのか（7日）",rom:"nanoka",id:"Tanggal tujuh / tujuh hari",cat:"Bab 5"},
  {jp:"ようか（8日）",rom:"youka",id:"Tanggal delapan / delapan hari",cat:"Bab 5"},
  {jp:"ここのか（9日）",rom:"kokonoka",id:"Tanggal sembilan / sembilan hari",cat:"Bab 5"},
  {jp:"とおか（10日）",rom:"tooka",id:"Tanggal sepuluh / sepuluh hari",cat:"Bab 5"},
  {jp:"じゅうよっか（14日）",rom:"juuyokka",id:"Tanggal empat belas / empat belas hari",cat:"Bab 5"},
  {jp:"はつか（20日）",rom:"hatsuka",id:"Tanggal dua puluh / dua puluh hari",cat:"Bab 5"},
  {jp:"にじゅうよっか（24日）",rom:"nijuuyokka",id:"Tanggal dua puluh empat / dua puluh empat hari",cat:"Bab 5"},
  {jp:"〜にち（〜日）",rom:"~nichi",id:"Tanggal ~ / ~ hari",cat:"Bab 5"},
  {jp:"なんにち（何日）",rom:"nannichi",id:"Tanggal berapa? / berapa hari?",cat:"Bab 5"},
  {jp:"いつ",rom:"itsu",id:"Kapan?",cat:"Bab 5"},
  {jp:"だします（出します）",rom:"dashimasu",id:"Mengumpulkan",cat:"Bab 6"},
  {jp:"ほうこくします（報告します）",rom:"houkoku shimasu",id:"Melaporkan",cat:"Bab 6"},
  {jp:"たべます（食べます）",rom:"tabemasu",id:"Makan",cat:"Bab 6"},
  {jp:"のみます（飲みます）",rom:"nomimasu",id:"Minum",cat:"Bab 6"},
  {jp:"[たばこを] すいます（吸います）",rom:"[tabako o] suimasu",id:"Menghisap (rokok), merokok",cat:"Bab 6"},
  {jp:"みます（見ます）",rom:"mimasu",id:"Melihat, menonton",cat:"Bab 6"},
  {jp:"ききます（聞きます）",rom:"kikimasu",id:"Mendengar, mendengarkan",cat:"Bab 6"},
  {jp:"よみます（読みます）",rom:"yomimasu",id:"Membaca",cat:"Bab 6"},
  {jp:"かきます（書きます）",rom:"kakimasu",id:"Menulis, menggambar, melukis",cat:"Bab 6"},
  {jp:"かいます（買います）",rom:"kaimasu",id:"Membeli",cat:"Bab 6"},
  {jp:"[しゃしんを] とります（取ります）",rom:"[shashin o] torimasu",id:"Mengambil (foto)",cat:"Bab 6"},
  {jp:"します",rom:"shimasu",id:"Mengerjakan, melakukan, berbuat",cat:"Bab 6"},
  {jp:"あいます（会います）",rom:"aimasu",id:"Bertemu, berjumpa",cat:"Bab 6"},
  {jp:"ごはん",rom:"gohan",id:"Nasi",cat:"Bab 6"},
  {jp:"あさごはん（朝ごはん）",rom:"asagohan",id:"Sarapan",cat:"Bab 6"},
  {jp:"ひるごはん（昼ごはん）",rom:"hirugohan",id:"Makan siang",cat:"Bab 6"},
  {jp:"ばんごはん（晩ごはん）",rom:"bangohan",id:"Makan malam",cat:"Bab 6"},
  {jp:"パン",rom:"pan",id:"Roti",cat:"Bab 6"},
  {jp:"たまご（卵）",rom:"tamago",id:"Telur",cat:"Bab 6"},
  {jp:"にく（肉）",rom:"niku",id:"Daging",cat:"Bab 6"},
  {jp:"さかな（魚）",rom:"sakana",id:"Ikan",cat:"Bab 6"},
  {jp:"やさい（野菜）",rom:"yasai",id:"Sayur",cat:"Bab 6"},
  {jp:"くだもの（果物）",rom:"kudamono",id:"Buah-buahan",cat:"Bab 6"},
  {jp:"みず（水）",rom:"mizu",id:"Air",cat:"Bab 6"},
  {jp:"おちゃ（お茶）",rom:"ocha",id:"Teh hijau",cat:"Bab 6"},
  {jp:"こうちゃ（紅茶）",rom:"koucha",id:"Teh",cat:"Bab 6"},
  {jp:"ぎゅうにゅう（牛乳） / ミルク",rom:"gyuunyuu / miruku",id:"Susu",cat:"Bab 6"},
  {jp:"ジュース",rom:"juusu",id:"Jus, sari buah",cat:"Bab 6"},
  {jp:"ビール",rom:"biiru",id:"Bir",cat:"Bab 6"},
  {jp:"[お]さけ（(お)酒）",rom:"[o]sake",id:"Minuman keras",cat:"Bab 6"},
  {jp:"たばこ",rom:"tabako",id:"Rokok",cat:"Bab 6"},
  {jp:"ビデオ",rom:"bideo",id:"Video",cat:"Bab 6"},
  {jp:"えいが（映画）",rom:"eiga",id:"Film",cat:"Bab 6"},
  {jp:"てがみ（手紙）",rom:"tegami",id:"Surat",cat:"Bab 6"},
  {jp:"CD / シーディ",rom:"shiidii",id:"CD",cat:"Bab 6"},
  {jp:"レポート",rom:"repooto",id:"Laporan",cat:"Bab 6"},
  {jp:"しゃしん（写真）",rom:"shashin",id:"Foto",cat:"Bab 6"},
  {jp:"みせ（店）",rom:"mise",id:"Toko",cat:"Bab 6"},
  {jp:"レストラン",rom:"resutoran",id:"Restoran",cat:"Bab 6"},
  {jp:"にわ（庭）",rom:"niwa",id:"Halaman, kebun",cat:"Bab 6"},
  {jp:"しゅくだい（宿題）",rom:"shukudai",id:"PR (pekerjaan rumah)",cat:"Bab 6"},
  {jp:"テニス",rom:"tenisu",id:"Tenis",cat:"Bab 6"},
  {jp:"サッカー",rom:"sakkaa",id:"Sepak bola",cat:"Bab 6"},
  {jp:"[お]はなみ（(お)花見）",rom:"[o]hanami",id:"Hanami (tradisi menikmati bunga sakura di musim semi)",cat:"Bab 6"},
  {jp:"なに（何）",rom:"nani",id:"Apa",cat:"Bab 6"},
  {jp:"いっしょに",rom:"issho ni",id:"Bersama-sama",cat:"Bab 6"},
  {jp:"ちょっと",rom:"chotto",id:"Sebentar, sedikit",cat:"Bab 6"},
  {jp:"いつも",rom:"itsumo",id:"Selalu",cat:"Bab 6"},
  {jp:"ときどき（時々）",rom:"tokidoki",id:"Kadang-kadang",cat:"Bab 6"},
  {jp:"それから",rom:"sorekara",id:"Setelah itu, kemudian",cat:"Bab 6"},
  {jp:"ええ",rom:"ee",id:"Ya",cat:"Bab 6"},
  {jp:"いいですね",rom:"ii desu ne",id:"Bagus ya/ Baik ya",cat:"Bab 6"},
  {jp:"わかりました",rom:"wakarimashita",id:"Mengerti/ Baik",cat:"Bab 6"},
  {jp:"きります（切ります）",rom:"kirimasu",id:"Memotong, menggunting",cat:"Bab 7"},
  {jp:"おくります（送ります）",rom:"okurimasu",id:"Mengirim",cat:"Bab 7"},
  {jp:"あげます",rom:"agemasu",id:"Memberikan",cat:"Bab 7"},
  {jp:"もらいます",rom:"moraimasu",id:"Menerima, mendapatkan",cat:"Bab 7"},
  {jp:"かします（貸します）",rom:"kashimasu",id:"Meminjamkan, menyewakan",cat:"Bab 7"},
  {jp:"かります（借ります）",rom:"karimasu",id:"Meminjam, menyewa",cat:"Bab 7"},
  {jp:"おしえます（教えます）",rom:"oshiemasu",id:"Mengajar",cat:"Bab 7"},
  {jp:"ならいます（習います）",rom:"naraimasu",id:"Belajar",cat:"Bab 7"},
  {jp:"[でんわを〜] かけます",rom:"[denwa o~] kakemasu",id:"Menelepon",cat:"Bab 7"},
  {jp:"て（手）",rom:"te",id:"Tangan",cat:"Bab 7"},
  {jp:"はし",rom:"hashi",id:"Sumpit",cat:"Bab 7"},
  {jp:"スプーン",rom:"supuun",id:"Sendok",cat:"Bab 7"},
  {jp:"ナイフ",rom:"naifu",id:"Pisau",cat:"Bab 7"},
  {jp:"フォーク",rom:"fooku",id:"Garpu",cat:"Bab 7"},
  {jp:"はさみ",rom:"hasami",id:"Gunting",cat:"Bab 7"},
  {jp:"パソコン",rom:"pasokon",id:"Komputer, PC",cat:"Bab 7"},
  {jp:"ケータイ",rom:"keetai",id:"HP",cat:"Bab 7"},
  {jp:"メール",rom:"meeru",id:"Email",cat:"Bab 7"},
  {jp:"ねんがじょう（年賀状）",rom:"nengajou",id:"Kartu tahun baru",cat:"Bab 7"},
  {jp:"パンチ",rom:"panchi",id:"Pelubang kertas",cat:"Bab 7"},
  {jp:"ホッチキス",rom:"hocchikisu",id:"Staplar",cat:"Bab 7"},
  {jp:"セロテープ",rom:"seroteepu",id:"Selotip",cat:"Bab 7"},
  {jp:"けしゴム（消しゴム）",rom:"keshigomu",id:"Penghapus karet",cat:"Bab 7"},
  {jp:"かみ（紙）",rom:"kami",id:"Kertas",cat:"Bab 7"},
  {jp:"はな（花）",rom:"hana",id:"Bunga",cat:"Bab 7"},
  {jp:"シャツ",rom:"shatsu",id:"Kemeja",cat:"Bab 7"},
  {jp:"プレゼント",rom:"purezento",id:"Hadiah, kado",cat:"Bab 7"},
  {jp:"クリスマス",rom:"kurisumasu",id:"Natal",cat:"Bab 7"},
  {jp:"これから",rom:"korekara",id:"Mulai dari sekarang",cat:"Bab 7"},
  {jp:"[~] すてきですね",rom:"[~] suteki desu ne",id:"(~) bagus ya / (~) indah ya",cat:"Bab 7"},
  {jp:"いらっしゃい",rom:"irasshai",id:"Selamat datang",cat:"Bab 7"},
  {jp:"しつれいします（失礼します）",rom:"shitsurei shimasu",id:"Permisi",cat:"Bab 7"},
  {jp:"どうぞ おあがりください（どうぞ お上がりください）",rom:"douzo oagari kudasai",id:"Silakan masuk!",cat:"Bab 7"},
  {jp:"[〜は] いかがですか",rom:"[~ wa] ikaga desu ka",id:"Bagaimana [~] (digunakan saat menawarkan sesuatu kepada orang)",cat:"Bab 7"},
  {jp:"いただきます",rom:"itadakimasu",id:"Selamat makan! (diucapkan sebelum menyantap makanan/minuman)",cat:"Bab 7"},
  {jp:"にもつ（荷物）",rom:"nimotsu",id:"Barang bawaan",cat:"Bab 7"},
  {jp:"おかね（お金）",rom:"okane",id:"Uang",cat:"Bab 7"},
  {jp:"きっぷ（切符）",rom:"kippu",id:"Karcis",cat:"Bab 7"},
  {jp:"ちち（父）",rom:"chichi",id:"Ayah, bapak",cat:"Bab 7"},
  {jp:"はは（母）",rom:"haha",id:"Ibu",cat:"Bab 7"},
  {jp:"おとうさん（お父さん）",rom:"otousan",id:"Ayah, bapak (ayah orang lain, juga digunakan untuk memanggil ayah kandung sendiri)",cat:"Bab 7"},
  {jp:"おかあさん（お母さん）",rom:"okaasan",id:"Ibu (ibu orang lain, juga digunakan untuk memanggil ibu kandung sendiri)",cat:"Bab 7"},
  {jp:"もう",rom:"mou",id:"Sudah",cat:"Bab 7"},
  {jp:"ハンサム[な]",rom:"hansamu [na]",id:"Tampan, gagah",cat:"Bab 8"},
  {jp:"きれい[な]",rom:"kirei [na]",id:"Bersih, cantik",cat:"Bab 8"},
  {jp:"しずか(静か)[な]",rom:"shizuka [na]",id:"Tenang, sunyi",cat:"Bab 8"},
  {jp:"にぎやか[な]",rom:"nigiyaka [na]",id:"Ramai",cat:"Bab 8"},
  {jp:"ゆうめい(有名)[な]",rom:"yuumei [na]",id:"Terkenal",cat:"Bab 8"},
  {jp:"しんせつ(親切)[な]",rom:"shinsetsu [na]",id:"Baik hati (tidak digunakan untuk keluarga sendiri)",cat:"Bab 8"},
  {jp:"げんき(元気)[な]",rom:"genki [na]",id:"Sehat walafiat",cat:"Bab 8"},
  {jp:"ひま(暇)[な]",rom:"hima [na]",id:"Senggang, luang",cat:"Bab 8"},
  {jp:"べんり(便利)[な]",rom:"benri [na]",id:"Praktis",cat:"Bab 8"},
  {jp:"すてき[な]",rom:"suteki [na]",id:"Bagus",cat:"Bab 8"},
  {jp:"おおきい(大きい)",rom:"ookii",id:"Besar",cat:"Bab 8"},
  {jp:"ちいさい(小さい)",rom:"chiisai",id:"Kecil",cat:"Bab 8"},
  {jp:"あたらしい(新しい)",rom:"atarashii",id:"Baru",cat:"Bab 8"},
  {jp:"ふるい(古い)",rom:"furui",id:"Lama, kuno, tua (tidak dipakai untuk umur)",cat:"Bab 8"},
  {jp:"いい(よい)",rom:"ii (yoi)",id:"Bagus, baik",cat:"Bab 8"},
  {jp:"わるい(悪い)",rom:"warui",id:"Jelek, buruk",cat:"Bab 8"},
  {jp:"あつい(暑い、熱い)",rom:"atsui",id:"Panas",cat:"Bab 8"},
  {jp:"さむい(寒い)",rom:"samui",id:"Dingin (untuk suhu udara)",cat:"Bab 8"},
  {jp:"つめたい(冷たい)",rom:"tsumetai",id:"Dingin (untuk rasa benda)",cat:"Bab 8"},
  {jp:"むずかしい(難しい)",rom:"muzukashii",id:"Susah, sulit",cat:"Bab 8"},
  {jp:"やさしい(易しい)",rom:"yasashii",id:"Gampang, mudah",cat:"Bab 8"},
  {jp:"たかい(高い)",rom:"takai",id:"Mahal, tinggi",cat:"Bab 8"},
  {jp:"やすい(安い)",rom:"yasui",id:"Murah",cat:"Bab 8"},
  {jp:"ひくい(低い)",rom:"hikui",id:"Rendah",cat:"Bab 8"},
  {jp:"おもしろい",rom:"omoshiroi",id:"Menarik",cat:"Bab 8"},
  {jp:"おいしい",rom:"oishii",id:"Enak, lezat",cat:"Bab 8"},
  {jp:"いそがしい(忙しい)",rom:"isogashii",id:"Sibuk",cat:"Bab 8"},
  {jp:"たのしい(楽しい)",rom:"tanoshii",id:"Menyenangkan",cat:"Bab 8"},
  {jp:"しろい(白い)",rom:"shiroi",id:"Putih",cat:"Bab 8"},
  {jp:"くろい(黒い)",rom:"kuroi",id:"Hitam",cat:"Bab 8"},
  {jp:"あかい(赤い)",rom:"akai",id:"Merah",cat:"Bab 8"},
  {jp:"あおい(青い)",rom:"aoi",id:"Biru",cat:"Bab 8"},
  {jp:"さくら(桜)",rom:"sakura",id:"Bunga Sakura",cat:"Bab 8"},
  {jp:"やま(山)",rom:"yama",id:"Gunung",cat:"Bab 8"},
  {jp:"まち(町)",rom:"machi",id:"Kota",cat:"Bab 8"},
  {jp:"たべもの(食べ物)",rom:"tabemono",id:"Makanan",cat:"Bab 8"},
  {jp:"ところ(所)",rom:"tokoro",id:"Tempat",cat:"Bab 8"},
  {jp:"りょう(寮)",rom:"ryou",id:"Asrama",cat:"Bab 8"},
  {jp:"べんきょう(勉強)",rom:"benkyou",id:"Pelajaran",cat:"Bab 8"},
  {jp:"せいかつ(生活)",rom:"seikatsu",id:"Kehidupan",cat:"Bab 8"},
  {jp:"[お]しごと(仕事)",rom:"[o]shigoto",id:"Pekerjaan",cat:"Bab 8"},
  {jp:"どう",rom:"dou",id:"Bagaimana",cat:"Bab 8"},
  {jp:"どんな〜",rom:"donna~",id:"Yang bagaimana",cat:"Bab 8"},
  {jp:"どれ",rom:"dore",id:"Yang mana (lebih dari 3)",cat:"Bab 8"},
  {jp:"とても",rom:"totemo",id:"Sangat~~ sekali",cat:"Bab 8"},
  {jp:"あまり",rom:"amari",id:"Tidak begitu ~ (diikuti kalimat negatif)",cat:"Bab 8"},
  {jp:"そして",rom:"soshite",id:"Dan, kemudian (untuk menyambung kalimat)",cat:"Bab 8"},
  {jp:"〜が、",rom:"~ga,",id:"~, tetapi",cat:"Bab 8"},
  {jp:"お元気(げんき)ですか",rom:"ogenki desu ka",id:"Apakabar?",cat:"Bab 8"},
  {jp:"そうですね",rom:"sou desu ne",id:"Bagaimana ya?",cat:"Bab 8"},
  {jp:"[~]もういっぱい いかがですか",rom:"[~] mou ippai ikaga desu ka",id:"Mau tambah [〜] secangkir lagi?",cat:"Bab 8"},
  {jp:"[いいえ] けっこうです",rom:"[iie] kekkou desu",id:"[Tidak,] terima kasih, saya sudah cukup",cat:"Bab 8"},
  {jp:"もう~です [ね]",rom:"mou~desu [ne]",id:"Sudah~ [ya]",cat:"Bab 8"},
  {jp:"そろそろ失礼(しつれい)します",rom:"sorosoro shitsurei shimasu",id:"Maaf, saya mau pamit dulu",cat:"Bab 8"},
  {jp:"またいらっしゃってください",rom:"mata irasshatte kudasai",id:"Silakan datang lagi!",cat:"Bab 8"},
  {jp:"わかります",rom:"wakarimasu",id:"Mengerti, paham",cat:"Bab 9"},
  {jp:"あります",rom:"arimasu",id:"Ada, memiliki",cat:"Bab 9"},
  {jp:"すき（好き）[な]",rom:"suki [na]",id:"Gemar, suka",cat:"Bab 9"},
  {jp:"きらい（嫌い）[な]",rom:"kirai [na]",id:"Tidak suka",cat:"Bab 9"},
  {jp:"じょうず（上手）[な]",rom:"jouzu [na]",id:"Pintar, pandai",cat:"Bab 9"},
  {jp:"へた（下手）[な]",rom:"heta [na]",id:"Tidak pandai, tidak pintar",cat:"Bab 9"},
  {jp:"りょうり（料理）",rom:"ryouri",id:"Masakan (～を します: memasak)",cat:"Bab 9"},
  {jp:"のみもの（飲み物）",rom:"nomimono",id:"Minuman",cat:"Bab 9"},
  {jp:"スポーツ",rom:"supootsu",id:"Olahraga (～を します: berolahraga)",cat:"Bab 9"},
  {jp:"やきゅう（野球）",rom:"yakyuu",id:"Baseball (～を します: bermain baseball)",cat:"Bab 9"},
  {jp:"ダンス",rom:"dansu",id:"Dansa (～を します: berdansa)",cat:"Bab 9"},
  {jp:"りょこう（旅行）",rom:"ryokou",id:"Tamasya (～を します: melakukan perjalanan)",cat:"Bab 9"},
  {jp:"おんがく（音楽）",rom:"ongaku",id:"Musik",cat:"Bab 9"},
  {jp:"うた（歌）",rom:"uta",id:"Lagu",cat:"Bab 9"},
  {jp:"クラシック",rom:"kurashikku",id:"Klasik",cat:"Bab 9"},
  {jp:"ジャズ",rom:"jazu",id:"Jazz",cat:"Bab 9"},
  {jp:"コンサート",rom:"konsaato",id:"Konser",cat:"Bab 9"},
  {jp:"カラオケ",rom:"karaoke",id:"Karaoke",cat:"Bab 9"},
  {jp:"かぶき（歌舞伎）",rom:"kabuki",id:"Kabuki (drama tradisional Jepang)",cat:"Bab 9"},
  {jp:"え（絵）",rom:"e",id:"Gambar",cat:"Bab 9"},
  {jp:"こまかい おかね（細かい お金）",rom:"komakai okane",id:"Uang kecil, receh",cat:"Bab 9"},
  {jp:"チケット",rom:"chiketto",id:"Tiket",cat:"Bab 9"},
  {jp:"じかん（時間）",rom:"jikan",id:"Jam, waktu",cat:"Bab 9"},
  {jp:"ようじ（用事）",rom:"youji",id:"Urusan",cat:"Bab 9"},
  {jp:"やくそく（約束）",rom:"yakusoku",id:"Janji (～を します: membuat janji)",cat:"Bab 9"},
  {jp:"アルバイト",rom:"arubaito",id:"Kerja paruh waktu",cat:"Bab 9"},
  {jp:"こども（子供）",rom:"kodomo",id:"Anak",cat:"Bab 9"},
  {jp:"ごしゅじん（ご主人）",rom:"goshujin",id:"Suami (menyebutkan suami orang lain)",cat:"Bab 9"},
  {jp:"おっと（夫）／しゅじん（主人）",rom:"otto / shujin",id:"Suami (sendiri)",cat:"Bab 9"},
  {jp:"おくさん（奥さん）",rom:"okusan",id:"Istri (menyebutkan istri orang lain)",cat:"Bab 9"},
  {jp:"つま（妻）／かない（家内）",rom:"tsuma / kanai",id:"Istri (sendiri)",cat:"Bab 9"},
  {jp:"よく",rom:"yoku",id:"Dengan baik",cat:"Bab 9"},
  {jp:"だいたい",rom:"daitai",id:"Kira-kira, hampir, sebagian besar",cat:"Bab 9"},
  {jp:"たくさん",rom:"takusan",id:"Banyak",cat:"Bab 9"},
  {jp:"すこし（少し）",rom:"sukoshi",id:"Sedikit",cat:"Bab 9"},
  {jp:"ぜんぜん（全然）",rom:"zenzen",id:"Sama sekali (diikuti kalimat negatif)",cat:"Bab 9"},
  {jp:"はやく（速く、早く）",rom:"hayaku",id:"Dengan cepat",cat:"Bab 9"},
  {jp:"～から",rom:"~kara",id:"Karena ～, sebab ～",cat:"Bab 9"},
  {jp:"どうして",rom:"doushite",id:"Mengapa",cat:"Bab 9"},
  {jp:"いいですよ",rom:"ii desu yo",id:"Boleh",cat:"Bab 9"},
  {jp:"ざんねんです [が]",rom:"zannen desu [ga]",id:"Sayang sekali (penyesalan)",cat:"Bab 9"},
  {jp:"[～は] ちょっと・・・",rom:"[~ wa] chotto...",id:"Maaf ya, saya tidak bisa [～]",cat:"Bab 9"},
  {jp:"だめですか",rom:"dame desu ka",id:"Tidak bisa/boleh, ya?",cat:"Bab 9"},
  {jp:"また こんど おねがいします",rom:"mata kondo onegaishimasu",id:"Maaf, lain kali saja (untuk menolak ajakan secara tidak langsung)",cat:"Bab 9"},

  // Bab 10
  {jp:"あります",rom:"arimasu",id:"Ada (untuk benda mati)",cat:"Bab 10"},
  {jp:"います",rom:"imasu",id:"Ada (untuk makhluk hidup)",cat:"Bab 10"},
  {jp:"いろいろ[な]",rom:"iroiro [na]",id:"Berbagai",cat:"Bab 10"},
  {jp:"おとこのひと（男の人）",rom:"otoko no hito",id:"Orang laki-laki",cat:"Bab 10"},
  {jp:"おんなのひと（女の人）",rom:"onna no hito",id:"Orang perempuan",cat:"Bab 10"},
  {jp:"おとこのこ（男の子）",rom:"otoko no ko",id:"Anak laki-laki",cat:"Bab 10"},
  {jp:"おんなのこ（女の子）",rom:"onna no ko",id:"Anak perempuan",cat:"Bab 10"},
  {jp:"いぬ（犬）",rom:"inu",id:"Anjing",cat:"Bab 10"},
  {jp:"ねこ（猫）",rom:"neko",id:"Kucing",cat:"Bab 10"},
  {jp:"パンダ",rom:"panda",id:"Panda",cat:"Bab 10"},
  {jp:"ぞう（象）",rom:"zou",id:"Gajah",cat:"Bab 10"},
  {jp:"き（木）",rom:"ki",id:"Pohon",cat:"Bab 10"},
  {jp:"もの（物）",rom:"mono",id:"Barang",cat:"Bab 10"},
  {jp:"でんち（電池）",rom:"denchi",id:"Baterai",cat:"Bab 10"},
  {jp:"はこ（箱）",rom:"hako",id:"Kotak",cat:"Bab 10"},
  {jp:"スイッチ",rom:"suicchi",id:"Tombol, sakelar",cat:"Bab 10"},
  {jp:"れいぞうこ（冷蔵庫）",rom:"reizouko",id:"Kulkas",cat:"Bab 10"},
  {jp:"テーブル",rom:"teeoburu",id:"Meja makan",cat:"Bab 10"},
  {jp:"ベッド",rom:"beddo",id:"Tempat tidur",cat:"Bab 10"},
  {jp:"たな（棚）",rom:"tana",id:"Lemari",cat:"Bab 10"},
  {jp:"ドア",rom:"doa",id:"Pintu",cat:"Bab 10"},
  {jp:"まど（窓）",rom:"mado",id:"Jendela",cat:"Bab 10"},
  {jp:"ポスト",rom:"posuto",id:"Kotak surat",cat:"Bab 10"},
  {jp:"ビル",rom:"biru",id:"Gedung",cat:"Bab 10"},
  {jp:"コンビニ",rom:"konbini",id:"Toko 24 jam",cat:"Bab 10"},
  {jp:"こうえん（公園）",rom:"kouen",id:"Taman",cat:"Bab 10"},
  {jp:"きっさてん（喫茶店）",rom:"kissaten",id:"Coffee shop",cat:"Bab 10"},
  {jp:"～や（屋）",rom:"~ya",id:"Toko ～",cat:"Bab 10"},
  {jp:"のりば（乗り場）",rom:"noriba",id:"Halte",cat:"Bab 10"},
  {jp:"けん（県）",rom:"ken",id:"Prefektur",cat:"Bab 10"},
  {jp:"うえ（上）",rom:"ue",id:"Atas",cat:"Bab 10"},
  {jp:"した（下）",rom:"shita",id:"Bawah",cat:"Bab 10"},
  {jp:"なか（中）",rom:"naka",id:"Dalam",cat:"Bab 10"},
  {jp:"まえ（前）",rom:"mae",id:"Depan, muka",cat:"Bab 10"},
  {jp:"うしろ（後ろ）",rom:"ushiro",id:"Belakang",cat:"Bab 10"},
  {jp:"みぎ（右）",rom:"migi",id:"Kanan",cat:"Bab 10"},
  {jp:"ひだり（左）",rom:"hidari",id:"Kiri",cat:"Bab 10"},
  {jp:"そと（外）",rom:"soto",id:"Luar",cat:"Bab 10"},
  {jp:"となり（隣）",rom:"tonari",id:"Sebelah",cat:"Bab 10"},
  {jp:"ちかく（近く）",rom:"chikaku",id:"Dekat",cat:"Bab 10"},
  {jp:"あいだ（間）",rom:"aida",id:"Antara",cat:"Bab 10"},
  {jp:"～や～（など）",rom:"~ya ~ (nado)",id:"～ dan, ～ (dan lain-lain)",cat:"Bab 10"},
  {jp:"ナンプラー",rom:"nanpuraa",id:"Kecap ikan",cat:"Bab 10"},
  {jp:"いちばんした（一番下）",rom:"ichiban shita",id:"Paling bawah",cat:"Bab 10"},

  // Bab 11
  {jp:"います",rom:"imasu",id:"Ada, mempunyai",cat:"Bab 11"},
  {jp:"います",rom:"imasu",id:"Ada (di ~)",cat:"Bab 11"},
  {jp:"かかります",rom:"kakarimasu",id:"Memakan, perlu (untuk waktu dan uang)",cat:"Bab 11"},
  {jp:"[かいしゃを] やすみます（休みます）",rom:"[kaisha o] yasumimasu",id:"Tidak masuk [kerja]",cat:"Bab 11"},
  {jp:"ひとつ（1つ）",rom:"hitotsu",id:"Satu (kata bantu bilangan untuk menghitung barang)",cat:"Bab 11"},
  {jp:"ふたつ（2つ）",rom:"futatsu",id:"Dua",cat:"Bab 11"},
  {jp:"みっつ（3つ）",rom:"mittsu",id:"Tiga",cat:"Bab 11"},
  {jp:"よっつ（4つ）",rom:"yottsu",id:"Empat",cat:"Bab 11"},
  {jp:"いつつ（5つ）",rom:"itsutsu",id:"Lima",cat:"Bab 11"},
  {jp:"むっつ（6つ）",rom:"muttsu",id:"Enam",cat:"Bab 11"},
  {jp:"ななつ（7つ）",rom:"nanatsu",id:"Tujuh",cat:"Bab 11"},
  {jp:"やっつ（8つ）",rom:"yattsu",id:"Delapan",cat:"Bab 11"},
  {jp:"ここのつ（9つ）",rom:"kokonotsu",id:"Sembilan",cat:"Bab 11"},
  {jp:"とお（10）",rom:"too",id:"Sepuluh",cat:"Bab 11"},
  {jp:"いくつ",rom:"ikutsu",id:"Berapa",cat:"Bab 11"},
  {jp:"ひとり（1人）",rom:"hitori",id:"Seorang",cat:"Bab 11"},
  {jp:"ふたり（2人）",rom:"futari",id:"Dua orang",cat:"Bab 11"},
  {jp:"～にん（～人）",rom:"~nin",id:"~ orang",cat:"Bab 11"},
  {jp:"～だい（～台）",rom:"~dai",id:"~ buah (kata bantu bilangan untuk menghitung mesin dan mobil)",cat:"Bab 11"},
  {jp:"～まい（～枚）",rom:"~mai",id:"~ lembar, helai (kata bantu bilangan untuk menghitung kertas dan perangko)",cat:"Bab 11"},
  {jp:"～かい（～回）",rom:"~kai",id:"~ kali",cat:"Bab 11"},
  {jp:"りんご",rom:"ringo",id:"Apel",cat:"Bab 11"},
  {jp:"みかん",rom:"mikan",id:"Jeruk",cat:"Bab 11"},
  {jp:"サンドイッチ",rom:"sandoicchi",id:"Sandwich",cat:"Bab 11"},
  {jp:"カレー[ライス]",rom:"karee [raisu]",id:"[Nasi dan] kare",cat:"Bab 11"},
  {jp:"アイスクリーム",rom:"aisukuriimu",id:"Es krim",cat:"Bab 11"},
  {jp:"きって（切手）",rom:"kitte",id:"Perangko",cat:"Bab 11"},
  {jp:"はがき",rom:"hagaki",id:"Kartu pos",cat:"Bab 11"},
  {jp:"ふうとう（封筒）",rom:"fuutou",id:"Amplop",cat:"Bab 11"},
  {jp:"りょうしん（両親）",rom:"ryoushin",id:"Orang tua",cat:"Bab 11"},
  {jp:"きょうだい（兄弟）",rom:"kyoudai",id:"Saudara, saudari",cat:"Bab 11"},
  {jp:"あに（兄）",rom:"ani",id:"Kakak laki-laki (untuk menyebutkan kakak sendiri)",cat:"Bab 11"},
  {jp:"おにいさん（お兄さん）",rom:"oniisan",id:"Kakak laki-laki (untuk menyebutkan kakak laki-laki orang lain)",cat:"Bab 11"},
  {jp:"あね（姉）",rom:"ane",id:"Kakak perempuan (untuk menyebutkan kakak sendiri)",cat:"Bab 11"},
  {jp:"おねえさん（お姉さん）",rom:"oneesan",id:"Kakak perempuan (untuk menyebutkan kakak perempuan orang lain)",cat:"Bab 11"},
  {jp:"おとうと（弟）",rom:"otouto",id:"Adik laki-laki",cat:"Bab 11"},
  {jp:"いもうと（妹）",rom:"imouto",id:"Adik perempuan",cat:"Bab 11"},
  {jp:"がいこく（外国）",rom:"gaikoku",id:"Luar negeri",cat:"Bab 11"},
  {jp:"りゅうがくせい（留学生）",rom:"ryuugakusei",id:"Pelajar asing",cat:"Bab 11"},
  {jp:"～じかん（時間）",rom:"~jikan",id:"~ jam",cat:"Bab 11"},
  {jp:"～しゅうかん（週間）",rom:"~shuukan",id:"~ minggu",cat:"Bab 11"},
  {jp:"～かげつ（か月）",rom:"~kagetsu",id:"~ bulan",cat:"Bab 11"},
  {jp:"ぜんぶで（全部で）",rom:"zenbu de",id:"Semuanya (untuk benda mati)",cat:"Bab 11"},
  {jp:"みんな",rom:"minna",id:"Semua (untuk orang)",cat:"Bab 11"},
  {jp:"～だけ",rom:"~dake",id:"Hanya ~, ~ saja",cat:"Bab 11"},
  {jp:"ふなびん（船便）",rom:"funabin",id:"Pos laut",cat:"Bab 11"},
  {jp:"こうくうびん（航空便）",rom:"koukuubin",id:"Pos udara",cat:"Bab 11"},
  {jp:"行（い）ってらっしゃい",rom:"itte rasshai",id:"Hati-hati!",cat:"Bab 11"},
  {jp:"行（い）ってきます",rom:"itte kimasu",id:"Aku berangkat",cat:"Bab 11"},
  {jp:"かしこまりました",rom:"kashikomarimashita",id:"Baik",cat:"Bab 11"},

  // Bab 12
  {jp:"かんたん（簡単）[な]",rom:"kantan [na]",id:"Mudah, gampang",cat:"Bab 12"},
  {jp:"ちかい（近い）",rom:"chikai",id:"Dekat",cat:"Bab 12"},
  {jp:"とおい（遠い）",rom:"tooi",id:"Jauh",cat:"Bab 12"},
  {jp:"はやい（速い、早い）",rom:"hayai",id:"Cepat",cat:"Bab 12"},
  {jp:"おそい（遅い）",rom:"osoi",id:"Lambat",cat:"Bab 12"},
  {jp:"おおい（多い）",rom:"ooi",id:"Banyak",cat:"Bab 12"},
  {jp:"すくない（少ない）",rom:"sukunai",id:"Sedikit",cat:"Bab 12"},
  {jp:"あたたかい（暖かい、温かい）",rom:"atatakai",id:"Hangat",cat:"Bab 12"},
  {jp:"すずしい（涼しい）",rom:"suzushii",id:"Sejuk",cat:"Bab 12"},
  {jp:"あまい（甘い）",rom:"amai",id:"Manis",cat:"Bab 12"},
  {jp:"からい（辛い）",rom:"karai",id:"Pedas",cat:"Bab 12"},
  {jp:"おもい（重い）",rom:"omoi",id:"Berat",cat:"Bab 12"},
  {jp:"かるい（軽い）",rom:"karui",id:"Ringan",cat:"Bab 12"},
  {jp:"いい [コーヒーが～]",rom:"ii [koohii ga ~]",id:"Lebih baik [kopi]",cat:"Bab 12"},
  {jp:"きせつ（季節）",rom:"kisetsu",id:"Musim",cat:"Bab 12"},
  {jp:"はる（春）",rom:"haru",id:"Musim semi",cat:"Bab 12"},
  {jp:"なつ（夏）",rom:"natsu",id:"Musim panas",cat:"Bab 12"},
  {jp:"あき（秋）",rom:"aki",id:"Musim gugur",cat:"Bab 12"},
  {jp:"てんき（天気）",rom:"tenki",id:"Cuaca",cat:"Bab 12"},
  {jp:"あめ（雨）",rom:"ame",id:"Hujan",cat:"Bab 12"},
  {jp:"ゆき（雪）",rom:"yuki",id:"Salju",cat:"Bab 12"},
  {jp:"くもり（曇り）",rom:"kumori",id:"Mendung",cat:"Bab 12"},
  {jp:"ホテル",rom:"hoteru",id:"Hotel",cat:"Bab 12"},
  {jp:"くうこう（空港）",rom:"kuukou",id:"Bandara",cat:"Bab 12"},
  {jp:"うみ（海）",rom:"umi",id:"Laut",cat:"Bab 12"},
  {jp:"せかい（世界）",rom:"sekai",id:"Dunia",cat:"Bab 12"},
  {jp:"[お] まつり（祭り）",rom:"[o] matsuri",id:"Perayaan",cat:"Bab 12"},
  {jp:"すきやき（すき焼き）",rom:"sukiyaki",id:"Sukiyaki (masakan berupa daging sapi dan sayur yang dimasak dalam panci)",cat:"Bab 12"},
  {jp:"さしみ（刺身）",rom:"sashimi",id:"Sashimi (ikan mentah dipotong tipis)",cat:"Bab 12"},
  {jp:"[お] すし",rom:"[o] sushi",id:"Sushi (nasi dicampur cuka yang di atasnya diberi ikan mentah)",cat:"Bab 12"},
  {jp:"てんぷら",rom:"tenpura",id:"Tempura (gorengan sari laut dan sayur yang dibalut tepung terigu)",cat:"Bab 12"},
  {jp:"ぶたにく（豚肉）",rom:"butaniku",id:"Daging babi",cat:"Bab 12"},
  {jp:"とりにく（とり肉）",rom:"toriniku",id:"Daging ayam",cat:"Bab 12"},
  {jp:"ぎゅうにく（牛肉）",rom:"gyuuniku",id:"Daging sapi",cat:"Bab 12"},
  {jp:"レモン",rom:"remon",id:"Lemon",cat:"Bab 12"},
  {jp:"いけばな（生け花）",rom:"ikebana",id:"Seni merangkai bunga",cat:"Bab 12"},
  {jp:"もみじ（紅葉）",rom:"momiji",id:"Daun maple",cat:"Bab 12"},
  {jp:"どちらも",rom:"dochira mo",id:"Dua-duanya, yang mana juga",cat:"Bab 12"},
  {jp:"いちばん",rom:"ichiban",id:"Paling",cat:"Bab 12"},
  {jp:"ずっと",rom:"zutto",id:"Jauh lebih",cat:"Bab 12"},
  {jp:"はじめて（初めて）",rom:"hajimete",id:"Untuk pertama kali",cat:"Bab 12"},
  {jp:"ただいま。",rom:"tadaima",id:"Saya kembali / Saya pulang",cat:"Bab 12"},
  {jp:"お帰（かえ）りなさい。",rom:"okaeri nasai",id:"Sudah pulang, ya",cat:"Bab 12"},
  {jp:"わあ、すごい人（ひと）ですね。",rom:"waa, sugoi hito desu ne",id:"Wah, banyak orang",cat:"Bab 12"},
  {jp:"疲（つか）れました。",rom:"tsukaremashita",id:"Lelah",cat:"Bab 12"},

  // Bab 13
  {jp:"あそびます（遊びます）",rom:"asobimasu",id:"Bermain",cat:"Bab 13"},
  {jp:"およぎます（泳ぎます）",rom:"oyogimasu",id:"Berenang",cat:"Bab 13"},
  {jp:"むかえます（迎えます）",rom:"mukaemasu",id:"Menjemput",cat:"Bab 13"},
  {jp:"つかれます（疲れます）",rom:"tsukaremasu",id:"Lelah (untuk menyatakan sudah lelah: つかれました)",cat:"Bab 13"},
  {jp:"けっこんします（結婚します）",rom:"kekkon shimasu",id:"Menikah",cat:"Bab 13"},
  {jp:"かいものします（買い物します）",rom:"kaimono shimasu",id:"Berbelanja",cat:"Bab 13"},
  {jp:"しょくじします（食事します）",rom:"shokuji shimasu",id:"Makan",cat:"Bab 13"},
  {jp:"さんぽします（散歩します）",rom:"sanpo shimasu",id:"Berjalan-jalan",cat:"Bab 13"},
  {jp:"たいへん（大変）[な]",rom:"taihen [na]",id:"Berat, susah",cat:"Bab 13"},
  {jp:"ほしい（欲しい）",rom:"hoshii",id:"Ingin, mau",cat:"Bab 13"},
  {jp:"ひろい（広い）",rom:"hiroi",id:"Luas",cat:"Bab 13"},
  {jp:"せまい（狭い）",rom:"semai",id:"Sempit",cat:"Bab 13"},
  {jp:"プール",rom:"puuru",id:"Kolam renang",cat:"Bab 13"},
  {jp:"びじゅつ（美術）",rom:"bijutsu",id:"Seni",cat:"Bab 13"},
  {jp:"つり（釣り）",rom:"tsuri",id:"Pancing",cat:"Bab 13"},
  {jp:"しゅうまつ（週末）",rom:"shuumatsu",id:"Akhir pekan",cat:"Bab 13"},
  {jp:"[お] しょうがつ（正月）",rom:"[o] shougatsu",id:"Tahun baru",cat:"Bab 13"},
  {jp:"〜ごろ",rom:"~goro",id:"Sekitar~, kira-kira~",cat:"Bab 13"},
  {jp:"なにか（何か）",rom:"nanika",id:"Sesuatu",cat:"Bab 13"},
  {jp:"どこか",rom:"dokoka",id:"Suatu tempat",cat:"Bab 13"},
  {jp:"のどが かわきます",rom:"nodo ga kawakimasu",id:"Haus (untuk menyatakan sudah haus: のどがかわきました)",cat:"Bab 13"},
  {jp:"おなかが すきます",rom:"onaka ga sukimasu",id:"Lapar (untuk menyatakan sudah lapar: おなかがすきました)",cat:"Bab 13"},
  {jp:"そう",rom:"sou",id:"Ya, mari (setuju dengan saran lawan bicara)",cat:"Bab 13"},
  {jp:"しましょう",rom:"shimashou",id:"Mari kita lakukan",cat:"Bab 13"},
  {jp:"ごちゅうもんは？（ご注文は？）",rom:"gochuumon wa?",id:"Mau pesan apa?",cat:"Bab 13"},
  {jp:"ていしょく（定食）",rom:"teishoku",id:"Menu paket",cat:"Bab 13"},
  {jp:"しょうしょう おまちください（少々 お待ちください）",rom:"shoushou omachi kudasai",id:"Mohon tunggu sebentar",cat:"Bab 13"},
  {jp:"べつべつに（別々に）",rom:"betsubetsu ni",id:"Masing-masing",cat:"Bab 13"},
];
