const vocab = [
  {jp:"わたし",rom:"watashi",id:"Saya / Aku",cat:"Bab 1"},
  {jp:"あなた",rom:"anata",id:"Kamu / Anda",cat:"Bab 1"},
  {jp:"あのひと / あのかた",rom:"ano hito / ano kata",id:"Orang itu / Beliau (sopan)",cat:"Bab 1"},
  {jp:"〜さん",rom:"~san",id:"Sebutan hormat (Pak/Bu/Sdr)",cat:"Bab 1"},
  {jp:"〜ちゃん",rom:"~chan",id:"Sebutan akrab / sayang",cat:"Bab 1"},
  {jp:"せんせい",rom:"sensei",id:"Guru / Sensei",cat:"Bab 1"},
  {jp:"〜さい",rom:"~sai",id:"... tahun (umur)",cat:"Bab 1"},
  {jp:"なんさい",rom:"nansai",id:"Berapa tahun (umur)?",cat:"Bab 1"},
  {jp:"おいくつ",rom:"oikutsu",id:"Berapa umur Anda? (sopan)",cat:"Bab 1"},
  {jp:"はい",rom:"hai",id:"Ya / Iya",cat:"Bab 1"},
  {jp:"いいえ",rom:"iie",id:"Tidak / Bukan",cat:"Bab 1"},
  {jp:"はじめまして",rom:"hajimemashite",id:"Senang berkenalan dengan Anda",cat:"Bab 1"},
  {jp:"〜からきました",rom:"~kara kimashita",id:"Saya berasal dari ~",cat:"Bab 1"},
  {jp:"どうぞよろしく",rom:"douzo yoroshiku",id:"Senang berkenalan (mohon bantuannya)",cat:"Bab 1"},
  {jp:"おなまえは？",rom:"onamae wa?",id:"Siapa nama Anda?",cat:"Bab 1"},
  {jp:"きょうし",rom:"kyoushi",id:"Guru / Pengajar",cat:"Bab 1"},
  {jp:"がくせい",rom:"gakusei",id:"Murid / Mahasiswa",cat:"Bab 1"},
  {jp:"ぎんこういん",rom:"ginkouin",id:"Pegawai bank",cat:"Bab 1"},
  {jp:"かいしゃいん",rom:"kaishain",id:"Karyawan perusahaan",cat:"Bab 1"},
  {jp:"いしゃ",rom:"isha",id:"Dokter",cat:"Bab 1"},
  {jp:"けんきゅうしゃ",rom:"kenkyuusha",id:"Peneliti",cat:"Bab 1"},
  {jp:"だいがく",rom:"daigaku",id:"Universitas",cat:"Bab 1"},
  {jp:"これ",rom:"kore",id:"Ini (dekat pembicara)",cat:"Bab 2"},
  {jp:"それ",rom:"sore",id:"Itu (dekat lawan bicara)",cat:"Bab 2"},
  {jp:"あれ",rom:"are",id:"Itu (jauh dari keduanya)",cat:"Bab 2"},
  {jp:"ほん",rom:"hon",id:"Buku",cat:"Bab 2"},
  {jp:"じしょ",rom:"jisho",id:"Kamus",cat:"Bab 2"},
  {jp:"ざっし",rom:"zasshi",id:"Majalah",cat:"Bab 2"},
  {jp:"しんぶん",rom:"shinbun",id:"Koran",cat:"Bab 2"},
  {jp:"ノート",rom:"nooto",id:"Buku catatan",cat:"Bab 2"},
  {jp:"てちょう",rom:"techou",id:"Buku saku / Agenda",cat:"Bab 2"},
  {jp:"めいし",rom:"meishi",id:"Kartu nama",cat:"Bab 2"},
  {jp:"えんぴつ",rom:"enpitsu",id:"Pensil",cat:"Bab 2"},
  {jp:"ボールペン",rom:"boorupen",id:"Bolpoin",cat:"Bab 2"},
  {jp:"かぎ",rom:"kagi",id:"Kunci",cat:"Bab 2"},
  {jp:"とけい",rom:"tokei",id:"Jam / Arloji",cat:"Bab 2"},
  {jp:"かさ",rom:"kasa",id:"Payung",cat:"Bab 2"},
  {jp:"かばん",rom:"kaban",id:"Tas",cat:"Bab 2"},
  {jp:"テレビ",rom:"terebi",id:"Televisi",cat:"Bab 2"},
  {jp:"ラジオ",rom:"rajio",id:"Radio",cat:"Bab 2"},
  {jp:"カメラ",rom:"kamera",id:"Kamera",cat:"Bab 2"},
  {jp:"コンピューター",rom:"konpyuutaa",id:"Komputer",cat:"Bab 2"},
  {jp:"くるま",rom:"kuruma",id:"Mobil",cat:"Bab 2"},
  {jp:"つくえ",rom:"tsukue",id:"Meja",cat:"Bab 2"},
  {jp:"いす",rom:"isu",id:"Kursi",cat:"Bab 2"},
  {jp:"おみやげ",rom:"omiyage",id:"Oleh-oleh / Suvenir",cat:"Bab 2"},
  {jp:"ここ",rom:"koko",id:"Di sini",cat:"Bab 3"},
  {jp:"そこ",rom:"soko",id:"Di situ",cat:"Bab 3"},
  {jp:"あそこ",rom:"asoko",id:"Di sana",cat:"Bab 3"},
  {jp:"どこ",rom:"doko",id:"Di mana?",cat:"Bab 3"},
  {jp:"こちら",rom:"kochira",id:"Ke sini / Ini (arah, sopan)",cat:"Bab 3"},
  {jp:"そちら",rom:"sochira",id:"Ke situ (arah, sopan)",cat:"Bab 3"},
  {jp:"あちら",rom:"achira",id:"Ke sana (arah, sopan)",cat:"Bab 3"},
  {jp:"どちら",rom:"dochira",id:"Yang mana? / Ke mana?",cat:"Bab 3"},
  {jp:"きょうしつ",rom:"kyoushitsu",id:"Ruang kelas",cat:"Bab 3"},
  {jp:"しょくどう",rom:"shokudou",id:"Kafetaria / Kantin",cat:"Bab 3"},
  {jp:"じむしょ",rom:"jimusho",id:"Kantor",cat:"Bab 3"},
  {jp:"かいぎしつ",rom:"kaigishitsu",id:"Ruang rapat",cat:"Bab 3"},
  {jp:"うけつけ",rom:"uketsuke",id:"Resepsionis / Meja penerima tamu",cat:"Bab 3"},
  {jp:"ロビー",rom:"robii",id:"Lobi",cat:"Bab 3"},
  {jp:"へや",rom:"heya",id:"Kamar / Ruangan",cat:"Bab 3"},
  {jp:"トイレ／おてあらい",rom:"toire / otearai",id:"Toilet / Kamar mandi",cat:"Bab 3"},
  {jp:"かいだん",rom:"kaidan",id:"Tangga",cat:"Bab 3"},
  {jp:"エレベーター",rom:"erebeetaa",id:"Lift / Elevator",cat:"Bab 3"},
  {jp:"エスカレーター",rom:"esukareetaa",id:"Eskalator",cat:"Bab 3"},
  {jp:"ちか",rom:"chika",id:"Lantai bawah tanah / Basement",cat:"Bab 3"},
  {jp:"〜かい",rom:"~kai / ~gai",id:"Lantai ke~ (gedung)",cat:"Bab 3"},
  {jp:"なんがい",rom:"nangai",id:"Lantai berapa?",cat:"Bab 3"},
  {jp:"うりば",rom:"uriba",id:"Bagian / Departemen toko",cat:"Bab 3"},
  {jp:"いくら",rom:"ikura",id:"Berapa harganya?",cat:"Bab 3"},
  {jp:"〜えん",rom:"~en",id:"~ yen (mata uang Jepang)",cat:"Bab 3"},
  {jp:"いま",rom:"ima",id:"Sekarang",cat:"Bab 4"},
  {jp:"〜じ",rom:"~ji",id:"Jam ~ (pukul)",cat:"Bab 4"},
  {jp:"〜ふん／ぷん",rom:"~fun / ~pun",id:"~ menit",cat:"Bab 4"},
  {jp:"はん",rom:"han",id:"Setengah (30 menit)",cat:"Bab 4"},
  {jp:"なんじ",rom:"nanji",id:"Jam berapa?",cat:"Bab 4"},
  {jp:"なんぷん",rom:"nanpun",id:"Berapa menit?",cat:"Bab 4"},
  {jp:"ごぜん",rom:"gozen",id:"Pagi / AM",cat:"Bab 4"},
  {jp:"ごご",rom:"gogo",id:"Sore / PM",cat:"Bab 4"},
  {jp:"あさ",rom:"asa",id:"Pagi",cat:"Bab 4"},
  {jp:"ひる",rom:"hiru",id:"Siang",cat:"Bab 4"},
  {jp:"ばん／よる",rom:"ban / yoru",id:"Malam",cat:"Bab 4"},
  {jp:"おととい",rom:"ototoi",id:"Kemarin lusa",cat:"Bab 4"},
  {jp:"きのう",rom:"kinou",id:"Kemarin",cat:"Bab 4"},
  {jp:"きょう",rom:"kyou",id:"Hari ini",cat:"Bab 4"},
  {jp:"あした",rom:"ashita",id:"Besok",cat:"Bab 4"},
  {jp:"あさって",rom:"asatte",id:"Lusa",cat:"Bab 4"},
  {jp:"けさ",rom:"kesa",id:"Pagi ini",cat:"Bab 4"},
  {jp:"こんばん",rom:"konban",id:"Malam ini",cat:"Bab 4"},
  {jp:"まいにち",rom:"mainichi",id:"Setiap hari",cat:"Bab 4"},
  {jp:"まいあさ",rom:"maiasa",id:"Setiap pagi",cat:"Bab 4"},
  {jp:"げつようび",rom:"getsuyoubi",id:"Hari Senin",cat:"Bab 4"},
  {jp:"かようび",rom:"kayoubi",id:"Hari Selasa",cat:"Bab 4"},
  {jp:"すいようび",rom:"suiyoubi",id:"Hari Rabu",cat:"Bab 4"},
  {jp:"もくようび",rom:"mokuyoubi",id:"Hari Kamis",cat:"Bab 4"},
  {jp:"きんようび",rom:"kinyoubi",id:"Hari Jumat",cat:"Bab 4"},
  {jp:"どようび",rom:"doyoubi",id:"Hari Sabtu",cat:"Bab 4"},
  {jp:"にちようび",rom:"nichiyoubi",id:"Hari Minggu",cat:"Bab 4"},
  {jp:"やすみ",rom:"yasumi",id:"Hari libur / Istirahat",cat:"Bab 4"},
  {jp:"しけん",rom:"shiken",id:"Ujian / Tes",cat:"Bab 4"},
  {jp:"かいぎ",rom:"kaigi",id:"Rapat",cat:"Bab 4"},
  {jp:"えいが",rom:"eiga",id:"Film / Bioskop",cat:"Bab 4"},
  {jp:"おきます",rom:"okimasu",id:"Bangun (tidur)",cat:"Bab 4"},
  {jp:"ねます",rom:"nemasu",id:"Tidur",cat:"Bab 4"},
  {jp:"はたらきます",rom:"hatarakimasu",id:"Bekerja",cat:"Bab 4"},
  {jp:"やすみます",rom:"yasumimasu",id:"Beristirahat / Libur",cat:"Bab 4"},
  {jp:"べんきょうします",rom:"benkyou shimasu",id:"Belajar",cat:"Bab 4"},
  {jp:"おわります",rom:"owarimasu",id:"Selesai / Berakhir",cat:"Bab 4"},
  {jp:"いきます",rom:"ikimasu",id:"Pergi",cat:"Bab 5"},
  {jp:"きます",rom:"kimasu",id:"Datang",cat:"Bab 5"},
  {jp:"かえります",rom:"kaerimasu",id:"Pulang",cat:"Bab 5"},
  {jp:"がっこう",rom:"gakkou",id:"Sekolah",cat:"Bab 5"},
  {jp:"スーパー",rom:"suupaa",id:"Supermarket",cat:"Bab 5"},
  {jp:"えき",rom:"eki",id:"Stasiun (kereta)",cat:"Bab 5"},
  {jp:"ひこうき",rom:"hikouki",id:"Pesawat terbang",cat:"Bab 5"},
  {jp:"ふね",rom:"fune",id:"Kapal",cat:"Bab 5"},
  {jp:"でんしゃ",rom:"densha",id:"Kereta listrik",cat:"Bab 5"},
  {jp:"ちかてつ",rom:"chikatetsu",id:"Kereta bawah tanah / MRT",cat:"Bab 5"},
  {jp:"しんかんせん",rom:"shinkansen",id:"Kereta cepat (Shinkansen)",cat:"Bab 5"},
  {jp:"バス",rom:"basu",id:"Bus",cat:"Bab 5"},
  {jp:"タクシー",rom:"takushii",id:"Taksi",cat:"Bab 5"},
  {jp:"じてんしゃ",rom:"jitensha",id:"Sepeda",cat:"Bab 5"},
  {jp:"あるいて",rom:"aruite",id:"Dengan berjalan kaki",cat:"Bab 5"},
  {jp:"ともだち",rom:"tomodachi",id:"Teman",cat:"Bab 5"},
  {jp:"かれ",rom:"kare",id:"Dia (laki-laki) / Pacar",cat:"Bab 5"},
  {jp:"きょねん",rom:"kyonen",id:"Tahun lalu",cat:"Bab 5"},
  {jp:"ことし",rom:"kotoshi",id:"Tahun ini",cat:"Bab 5"},
  {jp:"らいねん",rom:"rainen",id:"Tahun depan",cat:"Bab 5"},
  {jp:"なんねん",rom:"nannen",id:"Tahun berapa?",cat:"Bab 5"},
  {jp:"たんじょうび",rom:"tanjoubi",id:"Hari ulang tahun",cat:"Bab 5"},
  {jp:"ふつう",rom:"futsuu",id:"Kereta lokal (lambat)",cat:"Bab 5"},
  {jp:"きゅうこう",rom:"kyuukou",id:"Kereta ekspres",cat:"Bab 5"},
  {jp:"とっきゅう",rom:"tokkyuu",id:"Kereta super ekspres",cat:"Bab 5"},
  {jp:"デパート",rom:"depaato",id:"Pusat perbelanjaan / Department store",cat:"Bab 5"},
  {jp:"ぎんこう",rom:"ginkou",id:"Bank",cat:"Bab 5"},
  {jp:"ゆうびんきょく",rom:"yuubinkyoku",id:"Kantor pos",cat:"Bab 5"},
  {jp:"としょかん",rom:"toshokan",id:"Perpustakaan",cat:"Bab 5"},
  {jp:"びじゅつかん",rom:"bijutsukan",id:"Museum seni",cat:"Bab 5"},
  {jp:"だします（出します）",rom:"dashimasu",id:"Mengumpulkan",cat:"Bab 6"},
  {jp:"ほうこくします（報告します）",rom:"houkoku shimasu",id:"Melaporkan",cat:"Bab 6"},
  {jp:"たべます（食べます）",rom:"tabemasu",id:"Makan",cat:"Bab 6"},
  {jp:"のみます（飲みます）",rom:"nomimasu",id:"Minum",cat:"Bab 6"},
  {jp:"[たばこを] すいます（吸います）",rom:"[tabako o] suimasu",id:"Menghisap (rokok), merokok",cat:"Bab 6"},
  {jp:"みます（見ます）",rom:"mimasu",id:"Melihat, menonton",cat:"Bab 6"},
  {jp:"ききます（聞きます）",rom:"kikimasu",id:"Mendengar, mendengarkan",cat:"Bab 6"},
  {jp:"よみます（読みます）",rom:"yomimasu",id:"Membaca",cat:"Bab 6"},
  {jp:"かきます（書きます）",rom:"kakimasu",id:"Menulis, menggambar, melukis",cat:"Bab 6"},
  {jp:"かいます（買います）",rom:"kaimasu",id:"Membeli",cat:"Bab 6"},
  {jp:"[しゃしんを] とります（取ります）",rom:"[shashin o] torimasu",id:"Mengambil (foto)",cat:"Bab 6"},
  {jp:"します",rom:"shimasu",id:"Mengerjakan, melakukan, berbuat",cat:"Bab 6"},
  {jp:"あいます（会います）",rom:"aimasu",id:"Bertemu, berjumpa",cat:"Bab 6"},
  {jp:"ごはん",rom:"gohan",id:"Nasi",cat:"Bab 6"},
  {jp:"あさごはん（朝ごはん）",rom:"asagohan",id:"Sarapan",cat:"Bab 6"},
  {jp:"ひるごはん（昼ごはん）",rom:"hirugohan",id:"Makan siang",cat:"Bab 6"},
  {jp:"ばんごはん（晩ごはん）",rom:"bangohan",id:"Makan malam",cat:"Bab 6"},
  {jp:"パン",rom:"pan",id:"Roti",cat:"Bab 6"},
  {jp:"たまご（卵）",rom:"tamago",id:"Telur",cat:"Bab 6"},
  {jp:"にく（肉）",rom:"niku",id:"Daging",cat:"Bab 6"},
  {jp:"さかな（魚）",rom:"sakana",id:"Ikan",cat:"Bab 6"},
  {jp:"やさい（野菜）",rom:"yasai",id:"Sayur",cat:"Bab 6"},
  {jp:"くだもの（果物）",rom:"kudamono",id:"Buah-buahan",cat:"Bab 6"},
  {jp:"みず（水）",rom:"mizu",id:"Air",cat:"Bab 6"},
  {jp:"おちゃ（お茶）",rom:"ocha",id:"Teh hijau",cat:"Bab 6"},
  {jp:"こうちゃ（紅茶）",rom:"koucha",id:"Teh",cat:"Bab 6"},
  {jp:"ぎゅうにゅう（牛乳） / ミルク",rom:"gyuunyuu / miruku",id:"Susu",cat:"Bab 6"},
  {jp:"ジュース",rom:"juusu",id:"Jus, sari buah",cat:"Bab 6"},
  {jp:"ビール",rom:"biiru",id:"Bir",cat:"Bab 6"},
  {jp:"[お]さけ（(お)酒）",rom:"[o]sake",id:"Minuman keras",cat:"Bab 6"},
  {jp:"たばこ",rom:"tabako",id:"Rokok",cat:"Bab 6"},
  {jp:"ビデオ",rom:"bideo",id:"Video",cat:"Bab 6"},
  {jp:"えいが（映画）",rom:"eiga",id:"Film",cat:"Bab 6"},
  {jp:"てがみ（手紙）",rom:"tegami",id:"Surat",cat:"Bab 6"},
  {jp:"CD / シーディ",rom:"shiidii",id:"CD",cat:"Bab 6"},
  {jp:"レポート",rom:"repooto",id:"Laporan",cat:"Bab 6"},
  {jp:"しゃしん（写真）",rom:"shashin",id:"Foto",cat:"Bab 6"},
  {jp:"みせ（店）",rom:"mise",id:"Toko",cat:"Bab 6"},
  {jp:"レストラン",rom:"resutoran",id:"Restoran",cat:"Bab 6"},
  {jp:"にわ（庭）",rom:"niwa",id:"Halaman, kebun",cat:"Bab 6"},
  {jp:"しゅくだい（宿題）",rom:"shukudai",id:"PR (pekerjaan rumah)",cat:"Bab 6"},
  {jp:"テニス",rom:"tenisu",id:"Tenis",cat:"Bab 6"},
  {jp:"サッカー",rom:"sakkaa",id:"Sepak bola",cat:"Bab 6"},
  {jp:"[お]はなみ（(お)花見）",rom:"[o]hanami",id:"Hanami (tradisi menikmati bunga sakura di musim semi)",cat:"Bab 6"},
  {jp:"なに（何）",rom:"nani",id:"Apa",cat:"Bab 6"},
  {jp:"いっしょに",rom:"issho ni",id:"Bersama-sama",cat:"Bab 6"},
  {jp:"ちょっと",rom:"chotto",id:"Sebentar, sedikit",cat:"Bab 6"},
  {jp:"いつも",rom:"itsumo",id:"Selalu",cat:"Bab 6"},
  {jp:"ときどき（時々）",rom:"tokidoki",id:"Kadang-kadang",cat:"Bab 6"},
  {jp:"それから",rom:"sorekara",id:"Setelah itu, kemudian",cat:"Bab 6"},
  {jp:"ええ",rom:"ee",id:"Ya",cat:"Bab 6"},
  {jp:"いいですね",rom:"ii desu ne",id:"Bagus ya/ Baik ya",cat:"Bab 6"},
  {jp:"わかりました",rom:"wakarimashita",id:"Mengerti/ Baik",cat:"Bab 6"},
  {jp:"きります（切ります）",rom:"kirimasu",id:"Memotong, menggunting",cat:"Bab 7"},
  {jp:"おくります（送ります）",rom:"okurimasu",id:"Mengirim",cat:"Bab 7"},
  {jp:"あげます",rom:"agemasu",id:"Memberikan",cat:"Bab 7"},
  {jp:"もらいます",rom:"moraimasu",id:"Menerima, mendapatkan",cat:"Bab 7"},
  {jp:"かします（貸します）",rom:"kashimasu",id:"Meminjamkan, menyewakan",cat:"Bab 7"},
  {jp:"かります（借ります）",rom:"karimasu",id:"Meminjam, menyewa",cat:"Bab 7"},
  {jp:"おしえます（教えます）",rom:"oshiemasu",id:"Mengajar",cat:"Bab 7"},
  {jp:"ならいます（習います）",rom:"naraimasu",id:"Belajar",cat:"Bab 7"},
  {jp:"[でんわを〜] かけます",rom:"[denwa o~] kakemasu",id:"Menelepon",cat:"Bab 7"},
  {jp:"て（手）",rom:"te",id:"Tangan",cat:"Bab 7"},
  {jp:"はし",rom:"hashi",id:"Sumpit",cat:"Bab 7"},
  {jp:"スプーン",rom:"supuun",id:"Sendok",cat:"Bab 7"},
  {jp:"ナイフ",rom:"naifu",id:"Pisau",cat:"Bab 7"},
  {jp:"フォーク",rom:"fooku",id:"Garpu",cat:"Bab 7"},
  {jp:"はさみ",rom:"hasami",id:"Gunting",cat:"Bab 7"},
  {jp:"パソコン",rom:"pasokon",id:"Komputer, PC",cat:"Bab 7"},
  {jp:"ケータイ",rom:"keetai",id:"HP",cat:"Bab 7"},
  {jp:"メール",rom:"meeru",id:"Email",cat:"Bab 7"},
  {jp:"ねんがじょう（年賀状）",rom:"nengajou",id:"Kartu tahun baru",cat:"Bab 7"},
  {jp:"パンチ",rom:"panchi",id:"Pelubang kertas",cat:"Bab 7"},
  {jp:"ホッチキス",rom:"hocchikisu",id:"Staplar",cat:"Bab 7"},
  {jp:"セロテープ",rom:"seroteepu",id:"Selotip",cat:"Bab 7"},
  {jp:"けしゴム（消しゴム）",rom:"keshigomu",id:"Penghapus karet",cat:"Bab 7"},
  {jp:"かみ（紙）",rom:"kami",id:"Kertas",cat:"Bab 7"},
  {jp:"はな（花）",rom:"hana",id:"Bunga",cat:"Bab 7"},
  {jp:"シャツ",rom:"shatsu",id:"Kemeja",cat:"Bab 7"},
  {jp:"プレゼント",rom:"purezento",id:"Hadiah, kado",cat:"Bab 7"},
  {jp:"クリスマス",rom:"kurisumasu",id:"Natal",cat:"Bab 7"},
  {jp:"これから",rom:"korekara",id:"Mulai dari sekarang",cat:"Bab 7"},
  {jp:"[~] すてきですね",rom:"[~] suteki desu ne",id:"(~) bagus ya / (~) indah ya",cat:"Bab 7"},
  {jp:"いらっしゃい",rom:"irasshai",id:"Selamat datang",cat:"Bab 7"},
  {jp:"しつれいします（失礼します）",rom:"shitsurei shimasu",id:"Permisi",cat:"Bab 7"},
  {jp:"どうぞ おあがりください（どうぞ お上がりください）",rom:"douzo oagari kudasai",id:"Silakan masuk!",cat:"Bab 7"},
  {jp:"[〜は] いかがですか",rom:"[~ wa] ikaga desu ka",id:"Bagaimana [~] (digunakan saat menawarkan sesuatu kepada orang)",cat:"Bab 7"},
  {jp:"いただきます",rom:"itadakimasu",id:"Selamat makan! (diucapkan sebelum menyantap makanan/minuman)",cat:"Bab 7"},
  {jp:"にもつ（荷物）",rom:"nimotsu",id:"Barang bawaan",cat:"Bab 7"},
  {jp:"おかね（お金）",rom:"okane",id:"Uang",cat:"Bab 7"},
  {jp:"きっぷ（切符）",rom:"kippu",id:"Karcis",cat:"Bab 7"},
  {jp:"ちち（父）",rom:"chichi",id:"Ayah, bapak",cat:"Bab 7"},
  {jp:"はは（母）",rom:"haha",id:"Ibu",cat:"Bab 7"},
  {jp:"おとうさん（お父さん）",rom:"otousan",id:"Ayah, bapak (ayah orang lain, juga digunakan untuk memanggil ayah kandung sendiri)",cat:"Bab 7"},
  {jp:"おかあさん（お母さん）",rom:"okaasan",id:"Ibu (ibu orang lain, juga digunakan untuk memanggil ibu kandung sendiri)",cat:"Bab 7"},
  {jp:"もう",rom:"mou",id:"Sudah",cat:"Bab 7"},
  {jp:"ハンサム[な]",rom:"hansamu [na]",id:"Tampan, gagah",cat:"Bab 8"},
  {jp:"きれい[な]",rom:"kirei [na]",id:"Bersih, cantik",cat:"Bab 8"},
  {jp:"しずか(静か)[な]",rom:"shizuka [na]",id:"Tenang, sunyi",cat:"Bab 8"},
  {jp:"にぎやか[な]",rom:"nigiyaka [na]",id:"Ramai",cat:"Bab 8"},
  {jp:"ゆうめい(有名)[な]",rom:"yuumei [na]",id:"Terkenal",cat:"Bab 8"},
  {jp:"しんせつ(親切)[な]",rom:"shinsetsu [na]",id:"Baik hati (tidak digunakan untuk keluarga sendiri)",cat:"Bab 8"},
  {jp:"げんき(元気)[な]",rom:"genki [na]",id:"Sehat walafiat",cat:"Bab 8"},
  {jp:"ひま(暇)[な]",rom:"hima [na]",id:"Senggang, luang",cat:"Bab 8"},
  {jp:"べんり(便利)[な]",rom:"benri [na]",id:"Praktis",cat:"Bab 8"},
  {jp:"すてき[な]",rom:"suteki [na]",id:"Bagus",cat:"Bab 8"},
  {jp:"おおきい(大きい)",rom:"ookii",id:"Besar",cat:"Bab 8"},
  {jp:"ちいさい(小さい)",rom:"chiisai",id:"Kecil",cat:"Bab 8"},
  {jp:"あたらしい(新しい)",rom:"atarashii",id:"Baru",cat:"Bab 8"},
  {jp:"ふるい(古い)",rom:"furui",id:"Lama, kuno, tua (tidak dipakai untuk umur)",cat:"Bab 8"},
  {jp:"いい(よい)",rom:"ii (yoi)",id:"Bagus, baik",cat:"Bab 8"},
  {jp:"わるい(悪い)",rom:"warui",id:"Jelek, buruk",cat:"Bab 8"},
  {jp:"あつい(暑い、熱い)",rom:"atsui",id:"Panas",cat:"Bab 8"},
  {jp:"さむい(寒い)",rom:"samui",id:"Dingin (untuk suhu udara)",cat:"Bab 8"},
  {jp:"つめたい(冷たい)",rom:"tsumetai",id:"Dingin (untuk rasa benda)",cat:"Bab 8"},
  {jp:"むずかしい(難しい)",rom:"muzukashii",id:"Susah, sulit",cat:"Bab 8"},
  {jp:"やさしい(易しい)",rom:"yasashii",id:"Gampang, mudah",cat:"Bab 8"},
  {jp:"たかい(高い)",rom:"takai",id:"Mahal, tinggi",cat:"Bab 8"},
  {jp:"やすい(安い)",rom:"yasui",id:"Murah",cat:"Bab 8"},
  {jp:"ひくい(低い)",rom:"hikui",id:"Rendah",cat:"Bab 8"},
  {jp:"おもしろい",rom:"omoshiroi",id:"Menarik",cat:"Bab 8"},
  {jp:"おいしい",rom:"oishii",id:"Enak, lezat",cat:"Bab 8"},
  {jp:"いそがしい(忙しい)",rom:"isogashii",id:"Sibuk",cat:"Bab 8"},
  {jp:"たのしい(楽しい)",rom:"tanoshii",id:"Menyenangkan",cat:"Bab 8"},
  {jp:"しろい(白い)",rom:"shiroi",id:"Putih",cat:"Bab 8"},
  {jp:"くろい(黒い)",rom:"kuroi",id:"Hitam",cat:"Bab 8"},
  {jp:"あかい(赤い)",rom:"akai",id:"Merah",cat:"Bab 8"},
  {jp:"あおい(青い)",rom:"aoi",id:"Biru",cat:"Bab 8"},
  {jp:"さくら(桜)",rom:"sakura",id:"Bunga Sakura",cat:"Bab 8"},
  {jp:"やま(山)",rom:"yama",id:"Gunung",cat:"Bab 8"},
  {jp:"まち(町)",rom:"machi",id:"Kota",cat:"Bab 8"},
  {jp:"たべもの(食べ物)",rom:"tabemono",id:"Makanan",cat:"Bab 8"},
  {jp:"ところ(所)",rom:"tokoro",id:"Tempat",cat:"Bab 8"},
  {jp:"りょう(寮)",rom:"ryou",id:"Asrama",cat:"Bab 8"},
  {jp:"べんきょう(勉強)",rom:"benkyou",id:"Pelajaran",cat:"Bab 8"},
  {jp:"せいかつ(生活)",rom:"seikatsu",id:"Kehidupan",cat:"Bab 8"},
  {jp:"[お]しごと(仕事)",rom:"[o]shigoto",id:"Pekerjaan",cat:"Bab 8"},
  {jp:"どう",rom:"dou",id:"Bagaimana",cat:"Bab 8"},
  {jp:"どんな〜",rom:"donna~",id:"Yang bagaimana",cat:"Bab 8"},
  {jp:"どれ",rom:"dore",id:"Yang mana (lebih dari 3)",cat:"Bab 8"},
  {jp:"とても",rom:"totemo",id:"Sangat~~ sekali",cat:"Bab 8"},
  {jp:"あまり",rom:"amari",id:"Tidak begitu ~ (diikuti kalimat negatif)",cat:"Bab 8"},
  {jp:"そして",rom:"soshite",id:"Dan, kemudian (untuk menyambung kalimat)",cat:"Bab 8"},
  {jp:"〜が、",rom:"~ga,",id:"~, tetapi",cat:"Bab 8"},
  {jp:"お元気(げんき)ですか",rom:"ogenki desu ka",id:"Apakabar?",cat:"Bab 8"},
  {jp:"そうですね",rom:"sou desu ne",id:"Bagaimana ya?",cat:"Bab 8"},
  {jp:"[~]もういっぱい いかがですか",rom:"[~] mou ippai ikaga desu ka",id:"Mau tambah [〜] secangkir lagi?",cat:"Bab 8"},
  {jp:"[いいえ] けっこうです",rom:"[iie] kekkou desu",id:"[Tidak,] terima kasih, saya sudah cukup",cat:"Bab 8"},
  {jp:"もう~です [ね]",rom:"mou~desu [ne]",id:"Sudah~ [ya]",cat:"Bab 8"},
  {jp:"そろそろ失礼(しつれい)します",rom:"sorosoro shitsurei shimasu",id:"Maaf, saya mau pamit dulu",cat:"Bab 8"},
  {jp:"またいらっしゃってください",rom:"mata irasshatte kudasai",id:"Silakan datang lagi!",cat:"Bab 8"},
  // Kanji N5
  {kanji:"一",unyomi:"いち",kunyomi:"ひ",id:"satu",example:"一日（いちにち）= satu hari",cat:"Kanji N5",type:"kanji"},
  {kanji:"二",unyomi:"に",kunyomi:"ふ",id:"dua",example:"二日（ふつか）= dua hari",cat:"Kanji N5",type:"kanji"},
  {kanji:"三",unyomi:"さん",kunyomi:"み",id:"tiga",example:"三日（みっか）= tiga hari",cat:"Kanji N5",type:"kanji"},
  {kanji:"四",unyomi:"し",kunyomi:"よ",id:"empat",example:"四月（しがつ）= bulan April",cat:"Kanji N5",type:"kanji"},
  {kanji:"五",unyomi:"ご",kunyomi:"いつ",id:"lima",example:"五日（いつか）= lima hari",cat:"Kanji N5",type:"kanji"},
  {kanji:"六",unyomi:"ろく",kunyomi:"む",id:"enam",example:"六月（ろくがつ）= bulan Juni",cat:"Kanji N5",type:"kanji"},
  {kanji:"七",unyomi:"しち",kunyomi:"なな",id:"tujuh",example:"七月（しちがつ）= bulan Juli",cat:"Kanji N5",type:"kanji"},
  {kanji:"八",unyomi:"はち",kunyomi:"や",id:"delapan",example:"八月（はちがつ）= bulan Agustus",cat:"Kanji N5",type:"kanji"},
  {kanji:"九",unyomi:"きゅう",kunyomi:"ここ",id:"sembilan",example:"九月（くがつ）= bulan September",cat:"Kanji N5",type:"kanji"},
  {kanji:"十",unyomi:"じゅう",kunyomi:"とお",id:"sepuluh",example:"十月（じゅうがつ）= bulan Oktober",cat:"Kanji N5",type:"kanji"},
  {kanji:"日",unyomi:"にち",kunyomi:"ひ",id:"hari / matahari",example:"日本（にほん）= Jepang | 毎日（まいにち）= setiap hari",cat:"Kanji N5",type:"kanji"},
  {kanji:"月",unyomi:"げつ",kunyomi:"つき",id:"bulan",example:"月曜日（げつようび）= hari Senin | 月光（げっこう）= cahaya bulan",cat:"Kanji N5",type:"kanji"},
  {kanji:"火",unyomi:"か",kunyomi:"ひ",id:"api / hari selasa",example:"火曜日（かようび）= hari Selasa | 火（ひ）= api",cat:"Kanji N5",type:"kanji"},
  {kanji:"水",unyomi:"すい",kunyomi:"みず",id:"air / hari rabu",example:"水曜日（すいようび）= hari Rabu | 水（みず）= air",cat:"Kanji N5",type:"kanji"},
  {kanji:"木",unyomi:"もく",kunyomi:"き",id:"pohon / hari kamis",example:"木曜日（もくようび）= hari Kamis | 木（き）= pohon",cat:"Kanji N5",type:"kanji"},
  {kanji:"金",unyomi:"きん",kunyomi:"かね",id:"emas / uang / hari jumat",example:"金曜日（きんようび）= hari Jumat | お金（おかね）= uang",cat:"Kanji N5",type:"kanji"},
  {kanji:"土",unyomi:"ど",kunyomi:"つち",id:"tanah / hari sabtu",example:"土曜日（どようび）= hari Sabtu | 土（つち）= tanah",cat:"Kanji N5",type:"kanji"},
  {kanji:"大",unyomi:"だい",kunyomi:"おお",id:"besar",example:"大学（だいがく）= universitas | 大きい（おおきい）= besar",cat:"Kanji N5",type:"kanji"},
  {kanji:"小",unyomi:"しょう",kunyomi:"ちい",id:"kecil",example:"小学校（しょうがっこう）= sekolah dasar | 小さい（ちいさい）= kecil",cat:"Kanji N5",type:"kanji"},
  {kanji:"人",unyomi:"じん",kunyomi:"ひと",id:"orang",example:"人（ひと）= orang | 日本人（にほんじん）= orang Jepang",cat:"Kanji N5",type:"kanji"},
  {kanji:"子",unyomi:"し",kunyomi:"こ",id:"anak",example:"子ども（こども）= anak | 男の子（おとこのこ）= anak laki-laki",cat:"Kanji N5",type:"kanji"},
  {kanji:"女",unyomi:"じょ",kunyomi:"おんな",id:"wanita / perempuan",example:"女性（じょせい）= wanita | 女の子（おんなのこ）= anak perempuan",cat:"Kanji N5",type:"kanji"},
  {kanji:"男",unyomi:"だん",kunyomi:"おとこ",id:"pria / laki-laki",example:"男性（だんせい）= pria | 男の子（おとこのこ）= anak laki-laki",cat:"Kanji N5",type:"kanji"},
  {kanji:"生",unyomi:"せい",kunyomi:"い",id:"hidup / lahir",example:"先生（せんせい）= guru | 生まれる（うまれる）= lahir",cat:"Kanji N5",type:"kanji"},
  {kanji:"先",unyomi:"せん",kunyomi:"さき",id:"depan / sebelumnya",example:"先生（せんせい）= guru | 先週（せんしゅう）= minggu lalu",cat:"Kanji N5",type:"kanji"},
  {kanji:"百",unyomi:"ひゃく",kunyomi:"もも",id:"seratus",example:"百円（ひゃくえん）= 100 yen | 百人（ひゃくにん）= 100 orang",cat:"Kanji N5",type:"kanji"},
  {kanji:"千",unyomi:"せん",kunyomi:"ち",id:"seribu",example:"千円（せんえん）= 1000 yen | 千人（せんにん）= 1000 orang",cat:"Kanji N5",type:"kanji"},
  {kanji:"山",unyomi:"さん",kunyomi:"やま",id:"gunung",example:"山（やま）= gunung | 富士山（ふじさん）= Gunung Fuji",cat:"Kanji N5",type:"kanji"},
  {kanji:"川",unyomi:"せん",kunyomi:"かわ",id:"sungai",example:"川（かわ）= sungai | 川を渡る（かわをわたる）= menyeberangi sungai",cat:"Kanji N5",type:"kanji"},
  {kanji:"中",unyomi:"ちゅう",kunyomi:"なか",id:"tengah / dalam",example:"中国（ちゅうごく）= China | 中（なか）= dalam",cat:"Kanji N5",type:"kanji"},
  {kanji:"上",unyomi:"じょう",kunyomi:"うえ",id:"atas",example:"上（うえ）= atas | 階段の上（かいだんのうえ）= atas tangga",cat:"Kanji N5",type:"kanji"},
  {kanji:"下",unyomi:"か",kunyomi:"した",id:"bawah",example:"下（した）= bawah | 階段の下（かいだんのした）= bawah tangga",cat:"Kanji N5",type:"kanji"},
  {kanji:"左",unyomi:"さ",kunyomi:"ひだり",id:"kiri",example:"左（ひだり）= kiri | 左手（ひだりて）= tangan kiri",cat:"Kanji N5",type:"kanji"},
  {kanji:"右",unyomi:"う",kunyomi:"みぎ",id:"kanan",example:"右（みぎ）= kanan | 右手（みぎて）= tangan kanan",cat:"Kanji N5",type:"kanji"},
  {kanji:"東",unyomi:"とう",kunyomi:"ひがし",id:"timur",example:"東京（とうきょう）= Tokyo | 東（ひがし）= timur",cat:"Kanji N5",type:"kanji"},
  {kanji:"西",unyomi:"せい",kunyomi:"にし",id:"barat",example:"西（にし）= barat | 東西南北（とうざいなんぼく）= empat arah",cat:"Kanji N5",type:"kanji"},
  {kanji:"南",unyomi:"なん",kunyomi:"みなみ",id:"selatan",example:"南（みなみ）= selatan | 南米（なんべい）= Amerika Selatan",cat:"Kanji N5",type:"kanji"},
  {kanji:"北",unyomi:"ほく",kunyomi:"きた",id:"utara",example:"北（きた）= utara | 北海道（ほっかいどう）= Hokkaido",cat:"Kanji N5",type:"kanji"},
  {kanji:"白",unyomi:"はく",kunyomi:"しろ",id:"putih",example:"白（しろ）= putih | 白い（しろい）= putih",cat:"Kanji N5",type:"kanji"},
  {kanji:"黒",unyomi:"こく",kunyomi:"くろ",id:"hitam",example:"黒（くろ）= hitam | 黒い（くろい）= hitam",cat:"Kanji N5",type:"kanji"},
  {kanji:"赤",unyomi:"せき",kunyomi:"あか",id:"merah",example:"赤（あか）= merah | 赤い（あかい）= merah",cat:"Kanji N5",type:"kanji"},
  {kanji:"青",unyomi:"せい",kunyomi:"あお",id:"biru",example:"青（あお）= biru | 青い（あおい）= biru",cat:"Kanji N5",type:"kanji"},
  {kanji:"多",unyomi:"た",kunyomi:"おお",id:"banyak",example:"多い（おおい）= banyak | 多くの人（おおくのひと）= banyak orang",cat:"Kanji N5",type:"kanji"},
  {kanji:"少",unyomi:"しょう",kunyomi:"すく",id:"sedikit",example:"少ない（すくない）= sedikit | 少しずつ（すこしずつ）= sedikit demi sedikit",cat:"Kanji N5",type:"kanji"},
  {kanji:"古",unyomi:"こ",kunyomi:"ふる",id:"lama / kuno",example:"古い（ふるい）= lama | 古都（こと）= kota kuno",cat:"Kanji N5",type:"kanji"},
  {kanji:"新",unyomi:"しん",kunyomi:"あたら",id:"baru",example:"新しい（あたらしい）= baru | 新幹線（しんかんせん）= kereta cepat",cat:"Kanji N5",type:"kanji"},
  {kanji:"長",unyomi:"ちょう",kunyomi:"なが",id:"panjang / tua",example:"長い（ながい）= panjang | 長年（ちょうねん）= bertahun-tahun",cat:"Kanji N5",type:"kanji"},
  {kanji:"短",unyomi:"たん",kunyomi:"みじか",id:"pendek",example:"短い（みじかい）= pendek | 短編（たんぺん）= cerita pendek",cat:"Kanji N5",type:"kanji"},
  {kanji:"高",unyomi:"こう",kunyomi:"たか",id:"tinggi",example:"高い（たかい）= tinggi | 高校（こうこう）= sekolah menengah atas",cat:"Kanji N5",type:"kanji"},
  {kanji:"低",unyomi:"てい",kunyomi:"ひく",id:"rendah",example:"低い（ひくい）= rendah | 低気圧（ていきあつ）= tekanan rendah",cat:"Kanji N5",type:"kanji"},
  {kanji:"行",unyomi:"こう",kunyomi:"い",id:"pergi / baris",example:"行く（いく）= pergi | 銀行（ぎんこう）= bank",cat:"Kanji N5",type:"kanji"},
  {kanji:"来",unyomi:"らい",kunyomi:"く",id:"datang",example:"来る（くる）= datang | 来週（らいしゅう）= minggu depan",cat:"Kanji N5",type:"kanji"},
  {kanji:"見",unyomi:"けん",kunyomi:"み",id:"melihat",example:"見る（みる）= melihat | 見学（けんがく）= kunjungan belajar",cat:"Kanji N5",type:"kanji"},
  {kanji:"食",unyomi:"しょく",kunyomi:"た",id:"makan",example:"食べる（たべる）= makan | 食事（しょくじ）= makanan",cat:"Kanji N5",type:"kanji"},
];
