const kanjiDatabase = [
  // Bab 1
  { bab: "Bab 1", kanji: "日", onyomi: "ニチ / ジツ", kunyomi: "ひ / か", meaning: "matahari, hari", example: "日本 (にほん)" },
  { bab: "Bab 1", kanji: "月", onyomi: "ゲツ / ガツ", kunyomi: "つき", meaning: "bulan", example: "月曜日 (げつようび)" },
  { bab: "Bab 1", kanji: "木", onyomi: "モク / ボク", kunyomi: "き", meaning: "pohon", example: "木曜日 (もくようび)" },
  { bab: "Bab 1", kanji: "山", onyomi: "サン", kunyomi: "やま", meaning: "gunung", example: "富士山 (ふじさん)" },
  { bab: "Bab 1", kanji: "川", onyomi: "セン", kunyomi: "かわ", meaning: "sungai", example: "川 (かわ)" },
  { bab: "Bab 1", kanji: "田", onyomi: "デン", kunyomi: "た", meaning: "sawah", example: "田んぼ (たんぼ)" },
  { bab: "Bab 1", kanji: "人", onyomi: "ジン / ニン", kunyomi: "ひと", meaning: "orang", example: "日本人 (にほんじん)" },
  { bab: "Bab 1", kanji: "口", onyomi: "コウ / ク", kunyomi: "くち", meaning: "mulut", example: "入口 (いりぐち)" },
  { bab: "Bab 1", kanji: "入", onyomi: "ニュウ", kunyomi: "い.る / はい.る", meaning: "masuk, pintu masuk", example: "入口 (いりぐち)" },
  { bab: "Bab 1", kanji: "車", onyomi: "シャ", kunyomi: "くるま", meaning: "mobil", example: "電車 (でんしゃ)" },
  { bab: "Bab 1", kanji: "門", onyomi: "モン", kunyomi: "かど", meaning: "gerbang", example: "正門 (せいもん)" },

  // Bab 2
  { bab: "Bab 2", kanji: "火", onyomi: "カ", kunyomi: "ひ", meaning: "api", example: "火曜日 (かようび)" },
  { bab: "Bab 2", kanji: "水", onyomi: "スイ", kunyomi: "みず", meaning: "air", example: "水曜日 (すいようび)" },
  { bab: "Bab 2", kanji: "金", onyomi: "キン / コン", kunyomi: "かね", meaning: "emas, uang", example: "お金 (おかね)" },
  { bab: "Bab 2", kanji: "土", onyomi: "ド / ト", kunyomi: "つち", meaning: "tanah, daratan", example: "土曜日 (どようび)" },
  { bab: "Bab 2", kanji: "子", onyomi: "シ / ス", kunyomi: "こ", meaning: "anak", example: "子ども (こども)" },
  { bab: "Bab 2", kanji: "女", onyomi: "ジョ / ニョ", kunyomi: "おんな", meaning: "wanita", example: "女性 (じょせい)" },
  { bab: "Bab 2", kanji: "学", onyomi: "ガク", kunyomi: "まな.ぶ", meaning: "belajar", example: "学生 (がくせい)" },
  { bab: "Bab 2", kanji: "生", onyomi: "セイ / ショウ", kunyomi: "い.きる / う.まれる", meaning: "hidup, lahir", example: "先生 (せんせい)" },
  { bab: "Bab 2", kanji: "先", onyomi: "セン", kunyomi: "さき", meaning: "sebelumnya, lebih dulu", example: "先週 (せんしゅう)" },
  { bab: "Bab 2", kanji: "私", onyomi: "シ", kunyomi: "わたし", meaning: "saya, aku, privasi", example: "私 (わたし)" },

  // Bab 3
  { bab: "Bab 3", kanji: "一", onyomi: "イチ / イツ", kunyomi: "ひと", meaning: "satu", example: "一つ (ひとつ)" },
  { bab: "Bab 3", kanji: "二", onyomi: "ニ", kunyomi: "ふた", meaning: "dua", example: "二つ (ふたつ)" },
  { bab: "Bab 3", kanji: "三", onyomi: "サン", kunyomi: "みっ", meaning: "tiga", example: "三つ (みっつ)" },
  { bab: "Bab 3", kanji: "四", onyomi: "シ", kunyomi: "よん / よ", meaning: "empat", example: "四つ (よっつ)" },
  { bab: "Bab 3", kanji: "五", onyomi: "ゴ", kunyomi: "いつ", meaning: "lima", example: "五つ (いつつ)" },
  { bab: "Bab 3", kanji: "六", onyomi: "ロク", kunyomi: "むっ", meaning: "enam", example: "六つ (むっつ)" },
  { bab: "Bab 3", kanji: "七", onyomi: "シチ", kunyomi: "なな", meaning: "tujuh", example: "七つ (ななつ)" },
  { bab: "Bab 3", kanji: "八", onyomi: "ハチ", kunyomi: "やっ", meaning: "delapan", example: "八つ (やっつ)" },
  { bab: "Bab 3", kanji: "九", onyomi: "キュウ / ク", kunyomi: "ここの", meaning: "sembilan", example: "九つ (ここのつ)" },
  { bab: "Bab 3", kanji: "十", onyomi: "ジュウ", kunyomi: "とお", meaning: "sepuluh", example: "十 (じゅう)" },
  { bab: "Bab 3", kanji: "百", onyomi: "ヒャク", kunyomi: "もも", meaning: "seratus", example: "百円 (ひゃくえん)" },
  { bab: "Bab 3", kanji: "千", onyomi: "セン", kunyomi: "ち", meaning: "seribu", example: "千円 (せんえん)" },
  { bab: "Bab 3", kanji: "万", onyomi: "マン / バン", kunyomi: "よろず", meaning: "sepuluh ribu, semua", example: "一万円 (いちまんえん)" },
  { bab: "Bab 3", kanji: "円", onyomi: "エン", kunyomi: "まる", meaning: "lingkaran, yen", example: "100円 (ひゃくえん)" },
  { bab: "Bab 3", kanji: "年", onyomi: "ネン", kunyomi: "とし", meaning: "tahun, usia", example: "三年 (さんねん)" },

  // Bab 4
  { bab: "Bab 4", kanji: "上", onyomi: "ジョウ", kunyomi: "うえ", meaning: "atas", example: "上 (うえ)" },
  { bab: "Bab 4", kanji: "下", onyomi: "カ / ゲ", kunyomi: "した", meaning: "bawah", example: "下 (した)" },
  { bab: "Bab 4", kanji: "中", onyomi: "チュウ", kunyomi: "なか", meaning: "dalam, tengah", example: "中国 (ちゅうごく)" },
  { bab: "Bab 4", kanji: "大", onyomi: "ダイ / タイ", kunyomi: "おお", meaning: "hebat, besar", example: "大学 (だいがく)" },
  { bab: "Bab 4", kanji: "小", onyomi: "ショウ", kunyomi: "ちい", meaning: "kecil, sedikit", example: "小さい (ちいさい)" },
  { bab: "Bab 4", kanji: "本", onyomi: "ホン", kunyomi: "もと", meaning: "akar, asli, benar, utama", example: "日本 (にほん)" },
  { bab: "Bab 4", kanji: "半", onyomi: "ハン", kunyomi: "なか.ば", meaning: "setengah", example: "三時半 (さんじはん)" },
  { bab: "Bab 4", kanji: "分", onyomi: "ブン / フン", kunyomi: "わ.ける", meaning: "menit, pembagian, bagi", example: "十分 (じゅっぷん)" },
  { bab: "Bab 4", kanji: "力", onyomi: "リョク / リキ", kunyomi: "ちから", meaning: "kekuatan, kemampuan", example: "電力 (でんりょく)" },
  { bab: "Bab 4", kanji: "何", onyomi: "カ", kunyomi: "なに / なん", meaning: "apa", example: "何ですか (なんですか)" },

  // Bab 5
  { bab: "Bab 5", kanji: "明", onyomi: "メイ / ミョウ", kunyomi: "あか.るい", meaning: "terang, cerah", example: "明るい (あかるい)" },
  { bab: "Bab 5", kanji: "休", onyomi: "キュウ", kunyomi: "やす.む", meaning: "istirahat", example: "休み (やすみ)" },
  { bab: "Bab 5", kanji: "中", onyomi: "チュウ", kunyomi: "なか", meaning: "di dalam, tengah", example: "一日中 (いちにちじゅう)" },
  { bab: "Bab 5", kanji: "好", onyomi: "コウ", kunyomi: "す.き", meaning: "cinta, suka, favorit", example: "好き (すき)" },
  { bab: "Bab 5", kanji: "男", onyomi: "ダン / ナン", kunyomi: "おとこ", meaning: "laki-laki, pria", example: "男性 (だんせい)" },
  { bab: "Bab 5", kanji: "木", onyomi: "モク / ボク", kunyomi: "き", meaning: "kayu, pohon", example: "木 (き)" },
  { bab: "Bab 5", kanji: "林", onyomi: "リン", kunyomi: "はやし", meaning: "hutan kecil, pepohonan", example: "林 (はやし)" },
  { bab: "Bab 5", kanji: "間", onyomi: "カン / ケン", kunyomi: "あいだ", meaning: "di antara, interval", example: "時間 (じかん)" },
  { bab: "Bab 5", kanji: "畑", onyomi: "(umumnya kunyomi)", kunyomi: "はたけ", meaning: "ladang", example: "畑 (はたけ)" },
  { bab: "Bab 5", kanji: "岩", onyomi: "ガン", kunyomi: "いわ", meaning: "batu gunung", example: "岩 (いわ)" },

  // Bab 6
  { bab: "Bab 6", kanji: "目", onyomi: "モク", kunyomi: "め", meaning: "mata", example: "目 (め)" },
  { bab: "Bab 6", kanji: "耳", onyomi: "ジ", kunyomi: "みみ", meaning: "telinga", example: "耳 (みみ)" },
  { bab: "Bab 6", kanji: "手", onyomi: "シュ", kunyomi: "て", meaning: "tangan", example: "手 (て)" },
  { bab: "Bab 6", kanji: "足", onyomi: "ソク", kunyomi: "あし / た.りる", meaning: "kaki, berpasangan, cukup", example: "足りる (たりる)" },
  { bab: "Bab 6", kanji: "雨", onyomi: "ウ", kunyomi: "あめ", meaning: "hujan", example: "雨 (あめ)" },
  { bab: "Bab 6", kanji: "竹", onyomi: "チク", kunyomi: "たけ", meaning: "bambu", example: "竹 (たけ)" },
  { bab: "Bab 6", kanji: "米", onyomi: "ベイ / マイ", kunyomi: "こめ", meaning: "beras, Amerika", example: "米国 (べいこく)" },
  { bab: "Bab 6", kanji: "貝", onyomi: "バイ", kunyomi: "かい", meaning: "kerang", example: "貝 (かい)" },
  { bab: "Bab 6", kanji: "石", onyomi: "セキ / シャク", kunyomi: "いし", meaning: "batu", example: "石 (いし)" },
  { bab: "Bab 6", kanji: "糸", onyomi: "シ", kunyomi: "いと", meaning: "benang, tali", example: "糸 (いと)" },

  // Bab 7
  { bab: "Bab 7", kanji: "花", onyomi: "カ", kunyomi: "はな", meaning: "bunga", example: "花見 (はなみ)" },
  { bab: "Bab 7", kanji: "茶", onyomi: "チャ / サ", kunyomi: "(jarang)", meaning: "teh", example: "お茶 (おちゃ)" },
  { bab: "Bab 7", kanji: "肉", onyomi: "ニク", kunyomi: "(jarang)", meaning: "daging", example: "牛肉 (ぎゅうにく)" },
  { bab: "Bab 7", kanji: "文", onyomi: "ブン / モン", kunyomi: "ふみ", meaning: "pola, huruf, kalimat", example: "作文 (さくぶん)" },
  { bab: "Bab 7", kanji: "字", onyomi: "ジ", kunyomi: "あざ", meaning: "huruf, karakter", example: "漢字 (かんじ)" },
  { bab: "Bab 7", kanji: "物", onyomi: "ブツ / モツ", kunyomi: "もの", meaning: "barang, benda", example: "食べ物 (たべもの)" },
  { bab: "Bab 7", kanji: "牛", onyomi: "ギュウ", kunyomi: "うし", meaning: "sapi, banteng, lembu", example: "牛乳 (ぎゅうにゅう)" },
  { bab: "Bab 7", kanji: "馬", onyomi: "バ", kunyomi: "うま", meaning: "kuda", example: "馬 (うま)" },
  { bab: "Bab 7", kanji: "鳥", onyomi: "チョウ", kunyomi: "とり", meaning: "burung", example: "小鳥 (ことり)" },
  { bab: "Bab 7", kanji: "魚", onyomi: "ギョ", kunyomi: "さかな", meaning: "ikan", example: "魚 (さかな)" },

  // Bab 8
  { bab: "Bab 8", kanji: "石", onyomi: "セキ / シャク", kunyomi: "いし", meaning: "batu", example: "石 (いし)" },
  { bab: "Bab 8", kanji: "古", onyomi: "コ", kunyomi: "ふる.い", meaning: "lama", example: "古い (ふるい)" },
  { bab: "Bab 8", kanji: "長", onyomi: "チョウ", kunyomi: "なが.い", meaning: "panjang, tertua, ketua", example: "校長 (こうちょう)" },
  { bab: "Bab 8", kanji: "短", onyomi: "タン", kunyomi: "みじか.い", meaning: "pendek", example: "短い (みじかい)" },
  { bab: "Bab 8", kanji: "高", onyomi: "コウ", kunyomi: "たか.い", meaning: "tinggi, mahal", example: "高校 (こうこう)" },
  { bab: "Bab 8", kanji: "安", onyomi: "アン", kunyomi: "やす.い", meaning: "aman, murah", example: "安い (やすい)" },
  { bab: "Bab 8", kanji: "低", onyomi: "テイ", kunyomi: "ひく.い", meaning: "rendah", example: "低い (ひくい)" },
  { bab: "Bab 8", kanji: "暗", onyomi: "アン", kunyomi: "くら.い", meaning: "gelap", example: "暗い (くらい)" },
  { bab: "Bab 8", kanji: "多", onyomi: "タ", kunyomi: "おお.い", meaning: "banyak", example: "多い (おおい)" },
  { bab: "Bab 8", kanji: "少", onyomi: "ショウ", kunyomi: "すく.ない / すこ.し", meaning: "sedikit, kurang", example: "少ない (すくない)" }
];
